### ISSUE TITLE
phar file for android device

### ISSUE THREAD

**Issue by Jelly9912** [ImagicalCorp/PocketMine-0.13.0#1]
Can i get .phar file? I can't run this version from source code on android pocketmine ;/

**Comment by keithkfng** [comment]
I'll put it in a release folder, but I doubt android can run development versions.

**Comment by astersx** [comment]
Hey,  maybe pocketmine need another program to be arhived,  becouse for me dont work any versions of pocketmine arhived with program i use!!!!!

**Comment by keithkfng** [comment]
You may compile it into a phar here: pmt.mcpe.me
Please compile the folders inside the src folder.

**Comment by keithkfng** [comment]
Run DevTools. pmt.mcpe.me doesn't work for compiling PocketMine src phars.

**Comment by kennethgomad03** [comment]
how to compile where do i put src in plugin or server folder?

**Comment by keithkfng** [comment]
Get DevTools, download the zip file off this repo, copy the src file into the DevTools folder, then run /makeserver on the console once your server is running. It will compile it and drop a phar file for use.

**Comment by kennethgomad03** [comment]
could you please tell me more details?

**Comment by kennethgomad03** [comment]
what zip file code?

**Comment by kennethgomad03** [comment]
or could you give me pocketmine for 0.13 pls

**Comment by keithkfng** [comment]
Compile it yourself, we don't have enough time, as we are fixing bugs. Check the DevTools documentation for more info.
