### ISSUE TITLE
Snowball and inventory!

### ISSUE THREAD

**Issue by OfficialJoey** [ImagicalCorp/PocketMine-0.13.0#111]
Snowballs do not fly they just 'Sink'
When you get an item from the creative menu, then press a different slot that item disappears.

**Comment by keithkfng** [comment]
Too many slots.
Snowballs are more of an enhancement feature.

**Comment by legoboy0215** [comment]
Yes, I noticed the snowball issue.

**Comment by keithkfng** [comment]
Assign @ZombiePower please - slots issue

**Comment by legoboy0215** [comment]
Snowball is a new issue too. Low priority.

**Comment by keithkfng** [comment]
Yes, it's not REALLY essential is it?

**Comment by OfficialJoey** [comment]
Ok thanks :)
Also, i like the very quick response time :D
10/10

**Comment by keithkfng** [comment]
No problem - except for the fact I have to work till midnight nowadays

**Comment by legoboy0215** [comment]
lol We are all kinda students (Not like shog) so we can try our best :P

**Comment by OfficialJoey** [comment]
How old are you guys?

**Comment by keithkfng** [comment]
Yeah... He's too lazy XD

**Comment by legoboy0215** [comment]
Ok, that is a little TOO private :P

**Comment by OfficialJoey** [comment]
Haha sorry xD
What is a good version to get?
i currently have #150

**Comment by keithkfng** [comment]
#197

**Comment by legoboy0215** [comment]
Sorry, call it #197

**Comment by keithkfng** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/releases/tag/PM-1.7dev%23197

**Comment by OfficialJoey** [comment]
Ok thanks :)

**Comment by keithkfng** [comment]
@legoboy0215 would you mind renaming the file in the releases folder to #197 thanks

**Comment by legoboy0215** [comment]
Kay.

**Comment by thebigsmileXD** [comment]
Not actually.. Snowballs exists for a time now.. They changed to rapid fire now..

**Comment by keithkfng** [comment]
Thanks!

**Comment by ZombiePower** [comment]
What do you mean by sink? Do they just fall down on the floor?

**Comment by legoboy0215** [comment]
No, literally sink lol

**Comment by keithkfng** [comment]
What I really wanted you to fix was the slots... They don't seem to be working on Killa either... Even though you tried to fix it

**Comment by ZombiePower** [comment]
I tried fixing the fake hotbars, not the inventory lol

**Comment by ZombiePower** [comment]
Which, I believe worked.

**Comment by keithkfng** [comment]
Now it doesn't XD
Seems like chests are working, need clarification tomorrow.

**Comment by OfficialJoey** [comment]
I can test things tomorrow if you guys want?

**Comment by keithkfng** [comment]
I can test them, it's alright.

**Comment by OfficialJoey** [comment]
Ok

**Comment by ZombiePower** [comment]
Yes, so 7s didn't really do anything XD

**Comment by NML32** [comment]
Yup, snowballs just drop to the ground (straight down) when you try to throw them.

**Comment by ZombiePower** [comment]
Okay.. I will fix the vanishing items in inventories, tomorrow*, and will lock up Projectiles issue


*= depends, if I am not busy

**Comment by SkygridRex** [comment]
you has been broke some code in projectile.php and maybe in entity.php

**Comment by DRedDogPE** [comment]
```php
elseif($packet->face === 0xff){
					$aimPos = (new Vector3($packet->x / 32768, $packet->y / 32768, $packet->z / 32768))->normalize();

					if($this->isCreative()){
						$item = $this->inventory->getItemInHand();
					}elseif(!$this->inventory->getItemInHand()->deepEquals($packet->item)){
						$this->inventory->sendHeldItem($this);
						break;
					}else{
						$item = $this->inventory->getItemInHand();
					}

					$ev = new PlayerInteractEvent($this, $item, $aimPos, $packet->face, PlayerInteractEvent::RIGHT_CLICK_AIR);

					$this->server->getPluginManager()->callEvent($ev);

					if($ev->isCancelled()){
						$this->inventory->sendHeldItem($this);
						break;
					}

					if($item->getId() === Item::SNOWBALL){
						$nbt = new Compound("", [
							"Pos" => new Enum("Pos", [
								new Double("", $this->x),
								new Double("", $this->y + $this->getEyeHeight()),
								new Double("", $this->z)
							]),
							"Motion" => new Enum("Motion", [
								new Double("", $aimPos->x),
								new Double("", $aimPos->y),
								new Double("", $aimPos->z)
							]),
							"Rotation" => new Enum("Rotation", [
								new Float("", $this->yaw),
								new Float("", $this->pitch)
							]),
						]);

						$f = 1.5;
						$snowball = Entity::createEntity("Snowball", $this->chunk, $nbt, $this);
						$snowball->setMotion($snowball->getMotion()->multiply($f));
						if($this->isSurvival()){
							$item->setCount($item->getCount() - 1);
							$this->inventory->setItemInHand($item->getCount() > 0 ? $item : Item::get(Item::AIR));
						}
						if($snowball instanceof Projectile){
							$this->server->getPluginManager()->callEvent($projectileEv = new ProjectileLaunchEvent($snowball));
							if($projectileEv->isCancelled()){
								$snowball->kill();
							}else{
								$snowball->spawnToAll();
								$this->level->addSound(new LaunchSound($this), $this->getViewers());
							}
						}else{
							$snowball->spawnToAll();
						}
					}

					$this->setDataFlag(self::DATA_FLAGS, self::DATA_FLAG_ACTION, true);
					$this->startAction = $this->server->getTick();
				}
				break;
```
This is in pocketmine.php

**Comment by thebigsmileXD** [comment]
We did not. See any difference? I don't..

**Comment by OfficialJoey** [comment]
Sorry to bother you again, but what is the best available PocketMine right now?

**Comment by SkygridRex** [comment]
@OfficialJoey At the moment none

**Comment by SkygridRex** [comment]
@OfficialJoey All didn't work

**Comment by legoboy0215** [comment]
I fixed it
