### ISSUE TITLE
Plugin.yml Errors

### ISSUE THREAD

**Issue by Taki21** [ImagicalCorp/PocketMine-0.13.0#112]
Hello! My server was running properly with all the plugins and then after I get this weird error..........
![2015-11-24](https://cloud.githubusercontent.com/assets/14851895/11367155/dbc708d8-927f-11e5-99fc-8324a1209437.png)
These are all pocketmine plugins btw not mine!

Compliment: You guys are doing a good job ImagicalCorp! :+1:

**Comment by ZombiePower** [comment]
Show the error at least xD

**Comment by DRedDogPE** [comment]
ill look into it

**Comment by DRedDogPE** [comment]
Is your hard drive full?

**Comment by keithkfng** [comment]
Your phar is corrupted. There's nothing wrong with us. That's all I can say. Please contact the creator of the plugin.

**Comment by Taki21** [comment]
Corrupted? Im not using corrupted build its build #197 not Build 136! Like I Said These plugins were working! All of a sudden their not.

**Comment by Taki21** [comment]
@DRedDogPE  Its not full! :)

**Comment by keithkfng** [comment]
It's not our problem. I'm running latest src updates from the repo and they're working fine,

**Comment by Taki21** [comment]
So I gotta Compile the source to a phar?
