### ISSUE TITLE
Chest bug

### ISSUE THREAD

**Issue by KingDeadKnight** [ImagicalCorp/PocketMine-0.13.0#113]
Chest bugs at this time, we can put stuff in, but after close and reopen it, the stuff disappeared. And sometime reappear in the inventory. And don't know it's for you too, but all guys on my server have the same bug

Go on working so hard, you do great job :)

**Comment by keithkfng** [comment]
Yes, I have just tested this problem. Thanks for reporting!

**Comment by KyleBernhardt** [comment]
I can correlate this issue as well on build #197.  Shovel bug is fixed, but items are not staying in inventory.

**Comment by KyleBernhardt** [comment]
This issue still exists on on build #215.
![chest defect - 2](https://cloud.githubusercontent.com/assets/16007110/11387854/38a01108-92fd-11e5-8486-6b9342b1ca90.gif)

**Comment by keithkfng** [comment]
Nope, it works fine for me.
