### ISSUE TITLE
You can spawn mobs (villager, zombie and squid) even with "spawn-mobs = off"

### ISSUE THREAD

**Issue by Rodrigo294X** [ImagicalCorp/PocketMine-0.13.0#117]
I think this should not happen. At least I had not seen it before 1.7. (Note: "spawn-animals" is also disabled and I did not see them spawn naturally think it only happens to the spawn eggs.)

**Comment by keithkfng** [comment]
Yes, that only stops them from spawning naturally I think. That setting doesn't stop you from using spawn eggs.

**Comment by Rodrigo294X** [comment]
ok. I'm sorry.

**Comment by keithkfng** [comment]
No problem, happy to help.

**Comment by thebigsmileXD** [comment]
I'll still add an message when you spawn mobs that ai doesn't exist
