### ISSUE TITLE
Slots that don't exist are created

### ISSUE THREAD

**Issue by UltimateMcraft** [ImagicalCorp/PocketMine-0.13.0#120]
So let's say I got a sign, it creates a NEW hotbar slot sometimes, it even uses the inventory (...) as a slot.

**Comment by ZombiePower** [comment]
wasn't this fixed?

**Comment by keithkfng** [comment]
@TahaTheHacker please check if this was fixed before putting the bug label. Yes, this was fixed in build #215. Shouldn't happen again.

**Comment by ZombiePower** [comment]
@keithkfng :+1:
