### ISSUE TITLE
Crashdump build #197

### ISSUE THREAD

**Issue by carstenberger** [ImagicalCorp/PocketMine-0.13.0#122]
PocketMine-MP Crash Dump Wed Nov 25 15:22:55 UTC 2015

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 72 bytes)
File: /src/pocketmine/level/Level
Line: 2919
Type: E_ERROR

Code:
[2910] 
[2911] 	public function removeMetadata($metadataKey, Plugin $plugin){
[2912] 		$this->server->getLevelMetadata()->removeMetadata($this, $metadataKey, $plugin);
[2913] 	}
[2914] 
[2915] 	public function addEntityMotion($chunkX, $chunkZ, $entityId, $x, $y, $z){
[2916] 		if(!isset($this->motionToSend[$index = Level::chunkHash($chunkX, $chunkZ)])){
[2917] 			$this->motionToSend[$index] = [];
[2918] 		}
[2919] 		$this->motionToSend[$index][$entityId] = [$entityId, $x, $y, $z];
[2920] 	}
[2921] 
[2922] 	public function addEntityMovement($chunkX, $chunkZ, $entityId, $x, $y, $z, $yaw, $pitch, $headYaw = null){
[2923] 		if(!isset($this->moveToSend[$index = Level::chunkHash($chunkX, $chunkZ)])){
[2924] 			$this->moveToSend[$index] = [];
[2925] 		}
[2926] 		$this->moveToSend[$index][$entityId] = [$entityId, $x, $y, $z, $yaw, $headYaw === null ? $yaw : $headYaw, $pitch];
[2927] 	}
[2928] }
[2929] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.7dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Darwin server.x.nl 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Darwin, mac

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvtz3Dhy/leQkatOSg1Hw3lJokubcmztnevktc6S40sslwskwSFPfC0BajTe2vzt93UDfEjW
XrZy+SEq2yLxaHQ3vv66AfqXickKNQn81ep0tVmdnaynE9U0VTMJfpmYfY2uycXXiw8f3n+YTCeF
0lpuqe1Vnlc7FYtCFVWzFzr7pkSVCH9+sjxZ+aeLlQj3RmmhHlLZaoORh6bJ8MtUQmJuJI0SJws7
6giikywnuce6iY7rKrpTpshKdZyre5UfX9K/GJSjaRIszvyzX6eTOm+3WTkJEplrNZ1EVaxIafTO
IQij8eTj6dbUbZhnkUjaMjJZVYoGSt+rd8rIWBp5+KJwT39W+6m4YrHihRV/9IsVtGBBt+aFSTPt
/aBVc68a74etMqxbL+vI++GpdJoxFY8X6aS/tNKXLP1X+7LqtV8/q72M44vSZGb/rqL3wxdR2pZ3
f4VQfvgvPCjufxvj8QF/acFvnSUbZ0mWHP5LprUyh86mgsXdVNeqjD+/yMpYPYhzweYFAYv+k9Tp
d8sdfTnqRJ840b2bnhH5BTI/f3F2n7oJzvKzx05+bvbn3jYW9KylTvpiPvLqwu+8ulj8T169VwXE
/l6/0m+5oy3NTJTid6pk/J9yB/XKNs+dbxbL33b7vfonnL5Yfe/0JwLHLl+sH7l8sXnq8qdzf4/D
exf0pp9b48W/cY8I+q7OT506J+M9Iji4R0CBBCDMTSMjBPbnycFcHB4FYiCH29trF4ZRAye9aYv6
MKyqXMnyaPJlOtmqUjUyJ1LAKI1dhnx/dhKreywStlkeT4I5iKSpTBVVGLg8nU5knfEwfzmbY9g2
M3id/84fTGjkXZ6FNGd2whLaUhLDTt7IZgdisdQxyyttvDqXJqmaYlbmwl/P5rO5cKP+rJpS5eI/
rN6uMxDX0ohrVQv/DE3BehmsNuLqzY1YzP31S9FUlQkeytZbLlYnM38+8/3/9o8/XFxevLq++PrX
083XzUo88C/oVac1tFrPNhiJ12/YdLwv8D63vV8r3auNFn4rZDTpuRcNn+HnWjaw0EBV++4shFtr
1ZhM0byDq/5NvK7KJNsKYvzb5rY8+IS08FN1LxZr4fvBfB2s1uLjzWs2igY4siU3nl++v7759P7D
5ZtAXF0IYQEwGlRXjTn3wagLatxKyk+xOvfprZAP5PE9FD1fzHlSLXelR/uvmAXO/Q0179LMKC/P
tDmvkoRaVCnDXHk/t6rZn1flqKmJMM220OOsllrvqiY+/1f+waqViZ9XWxz+O2EwsJBc+OsjkiLL
sgIpKaeqJ6M0U5aStFuIEujOS/Jsm/YaWlNkmRVIh26cbSuqsGsA1iC494qbmsomjqqmf6/vazc+
zpIki9rc7K0HbUSZqvFAYCYrt/qcmjlJ2/2B6Xk8tGml4tEQKijO31z8+Orj5Q0b0prK0/JeufUI
d314z/ZFTsgR7yQCImLQtFid4oGwI2CNuOLh7zDce3cFLImbVGklOvWEbJQwKWqTEsAzKcInIgcb
ESqRlVHexgDfEJUDZknWdVVwVWO+l6lloqaiQk+jSaQIGyXvxL5qGydLZImAl7Mk4xXg4AYgy/ck
+Ce168UdxyqRcLEWu6r8gxGyrpVsBLmmgLERNnsP9QURtLV7l6pStPW2kTEEzG5LQr8VFtyW4uAm
bRTgiyZokcty26JmE1QfsctcpOgM71SI5dk3dipNfZ2qyFnxeCIUSI2pdXB8rMrZLrvLahVnclY1
22N6O75EtHytkq9vr99/3SzPvMVXmgc39oICcTtR5fZ2Qgt9ShX5jspBDeKhmlBoVIjkXzB+qcGM
tlp03mRNoQeelOEtRcxkkRKpLOOcN7mAYIvwYUkuDtGu09bEFUWDLWFJGReFEahYxVYtLmsFRT40
EY7lxH0mxV8o9DGEKcBzPQF0bUn8wXWKeZJQqpGAhFvFbpV0gkSrAcJY1QACW/fq6i1GmrSKyU9D
hwe1Qig1iL9gsunkwGJBASsAVyCCVA33wuEIwx019b2DGw4+ZXB0VQJSKHhQCGuLPFITWLuDOlK3
DbONAN5CRf6A09XPrcxpO7bZPcbey7xV4tAtCaY+gnC7HihREQt72M3tVjUBemnln9oihLcRTq/0
voxupL4D4ps7BNCM+j9iExifnZE0Km0qsCEggdEoopldhGMhQHYKNxTwmuYkSW7ZqZDairZE5NAQ
ln3NkIE9CK6megBHGgUXwByGetmrRl616rxNKEL5uIJInIrM/AGeMw3PihUlDEbhk7niEBZgn8WC
PMI2eM7KgCVRtNpDE8fqH/MqhGN1lZjuLJVnRWaIkwq1lXw+molrq8qcF880ba+NdNi0y1gxdrag
xGDldP7X7JckA1xAU6DhkkUl4IhuRbv9MKZl0G4r2FFRaJDPsM6WlfRYsUDMb5kqmJUNqEbG/8/V
L6DpP1Ce0t8/pbw2Vc3rO6rq9XHStEBIUV0AlnHa0JqdSv58sbJaXakmqzgdUSxqWjBiQnba9fHm
YylQTUwY4xEe4kHZSGMar1Cll4hQ+I3Y4bfcat2JcidnhqdYt8NuOeGSDETfEMmWjmiF90QhlOF4
+Oz7wWS25aEYLqxVRIlQs1tIV+tjO7c3AJ5UtR7MXM6dnfroWYWc1Utr9VY2IfbfQyWf23KOIuxZ
rzKcSBU3R7g5iN1Cli2n3LEWKEdauqeYdpzwBAwODZZXk6TjhmJA2Uy8t/mO34CItGrzuFckA4Ps
SjGoTrgVNWsOAzc4WrCN4uBHjoTvuJGxYmf3RiVNVXQUS3NdvzdmpdGewgi3dU+h8Ax+RvOorOZT
qbb+vmTUEyFyI2mWV4gzWCNsTTvl8GxQgGg7yKMagGqZQRaJ6rbZBcrZxun5prLTnm4fJQGqlOy0
sQS7ihv2f2AzJyIvQm2urNUOC91C1NFn738o6rYslaG96Es3QCO3mTCUOClzISKpykUCBJ4cK3EA
2sLU9VoyClWfE5luDsb01fVQ4Dd7Q7KnwvNHYKbcx8t6plMFtLLeWFYZci3X85ToYkt3bgPtXDQ6
nWbiTzikwL3nqIUB3NdXH6eYCw1C8M8ui01qWZvjuxfvsfhAnLjCYCgZNDtmNHQmXsWIp1TmyTGK
fFvFxAo4cwthSYu/qhwHZJ+dR7JGddLFAwUflUEyn9rApoU/ZSWqSJgF2CiGNuX6j1flVVcpDDU7
FUE0aQeuv6WCvaw99zquyXDKUmG7DVzR8YPwqdhwmYWqSu7uKkrNPJaqrtK8dVuBNDLUiVocayNN
C8AcbyPrWvBarEeLduezR+cG1RWRpDcssScmHurgRebyhkdwomGEuSmenRKIAl1bd56AQQR0qtNK
QA4gZVKSj+SDOelEZkbLw5nme204RnnrDn56f3MRCGZd/IlaHK5KHK5YUFbUOVewrJ5buVev3+JX
j3YrwjkCTOJsZRRxSoImhBpDyFnMXQohKrOZiWBEh1hqd+nIRf3j5o7DbC18TeFKBoZSq9Fihz4C
5ZlVpmKBDv+5DmWi2REHrVZjLRgONySZjlbu2kMoEJNdj1K/3Uk+xA6nWyICPgVR9UR0IPOd3Gsr
28kZ4egRfzOMXhVVW44TgHY1W6cEqU/S6MgAbqbHQKx+e6ps0Bpb3a2Mx1lH+GeLZ2czukplz5Gh
stJClRAT8d0IMRZtQy/V3piMqM8y37W8R9Kl+i6j47Ki41e9d1cDLhf1BQ0TRSK1Ya+yXxyNJW3O
wyoNqHoUollkUwkfwRo6jwMYENu56m8VnYRsbGhZEFYK5kpKML39TzaDHNptxjv5IORTv+AMFHF+
GPDweC8YpB9knLV6NM3tg3TacZDaqQ53NB7VCnESXU15bR0Di4OCOGoraRfh27UhC1rFh4Ndp/vs
e+Ud/+1kxmd0nMdb5fbXzeew53aPvksF4vR/Ja2u6jZ30twzpaYngm9LjkkP3iOl7QWcxzjS5Ely
ZQGuNnTl4lp9Rw908xUIW9x1W0q3122NYsdWfBaQTB620HCyIOWEZrkFSeiaXneSFuobuU0WYQbk
2yHu0s2e0QNLRnSdQDfowrbaHOtAYtHrKvme3AjXHl3wPG7p08mj1jqtszKpBhikFe09Lzkb3feh
EGL9yqrcF1Tmc4Ro+Ff3itK5xXWLoZsVpo9rQm63yD7ucqC/dqEakb4j3D1vjdWHxOnn9CF/WSjz
Fj+dDUzY3sBuQFN6LjkPFSC3VvXowug13RnyJZbKq5qy1RTvsIBu6ExXiqEySVApKzgb+amkPE+D
XGptaXcQjyMhwn3pGNUQLQpObWyC6wjPSaMdst2dfP3EKbvd7jmX5BnSjd2ViwdJ+da+UMEC+U6J
oNOGuwB2OikH4jM9ekgyUz46fyGJlgW7MmR828pGdOcFe2jrbqH5NPbc5S0fbjmLaa4YyOwChUQG
RV2KH6nOq7IC/CTo0ppCl1PSsFogfrx8dRMsXp5M12cP/nT5sJwuXvovY2Riy1qHplF4AcOcn87F
FvjW9m21PuLLbfVgVEkO0fRR6jXy0PgLDGFo/I6EsO0/b9cRDXYv+uc8M2ppPzJ59nvWN/vVacFf
b8IIlU06fBuXOWJHNkOD/bTfvbVN3r8kWQ6gs2jfZ2GJqfvebTw8FkNzilDmr2Y0/m/afWlbzHz6
TwOhvdjtB6NA3NdmMMZI0i0em359dckaLOiLQITKbpi8h/H8pco9Cfo05vvkBeHRN6PFfD1f4vHF
Wzo6R5vT03AThtFyHi83MlnKaLlK4ngVnoTr8OT0JFFr/IgXWOkqJReRC+3Clc4ehg1wR3c3wCfT
PqjEnTvRyuupJDkN42izDuehkslpspKx2iTzTXK6OlWbeLWMk/h0seH1dFpUgw81h5l+bGlmNwKD
TXWnSmSdpm/5pOQd+ME6arZBy17yJxN/5vOAb1lt3xaz9eTXX/8OVoe+WQ==
===END CRASH DUMP===

**Comment by DRedDogPE** [comment]
Out of ram
