### ISSUE TITLE
NetherCrop issue

### ISSUE THREAD

**Issue by SkygridRex** [ImagicalCorp/PocketMine-0.13.0#124]
@DRedDogPE Why you use my code without my authorization?

**Comment by DRedDogPE** [comment]
@SkygridRex I thought you wanted me to use it thats why you created that pull request on my repo

**Comment by SkygridRex** [comment]
But, i contribute you not give you my code

**Comment by DRedDogPE** [comment]
@SkygridRex so you want me to remove it then?

**Comment by SkygridRex** [comment]
At the moment not

**Comment by SkygridRex** [comment]
I'll talk with you later

**Comment by DRedDogPE** [comment]
@SkygridRex Talk on gitter.
