### ISSUE TITLE
Versioning issues

### ISSUE THREAD

**Issue by PEMapModder** [ImagicalCorp/PocketMine-0.13.0#127]
It is irresponsible for a branched version of a project to be named as if it is part of the main development. In the future, users would get confused whether 1.7 is the official 1.7 or this unofficial version. I urge you to rename the project in another way, like what williamtdr did with Katana and Steadfast 2.

**Comment by DRedDogPE** [comment]
i thought was clear in the readme.md:

# This is a third-party PM build!

**Comment by thebigsmileXD** [comment]
Yea.. Its easy to see because its right on top..

**Comment by PEMapModder** [comment]
Yes, but the versioning doesn't state that. Calling it 1.7 is extremely confusing.

**Comment by PEMapModder** [comment]
For example, people come to PocketMine support for this, thinking this is PocketMine 1.7. Third party or not, please change the name a little bit, ok?

**Comment by PEMapModder** [comment]
Is there somewhere I can talk directly, like a chatroom?

**Comment by DRedDogPE** [comment]
https://gitter.im/ImagicalCorp/PocketMine-0.13.0 maybe

**Comment by matcracker** [comment]
I agree this.

**Comment by keithkfng** [comment]
Will be changed.
