### ISSUE TITLE
File from releases

### ISSUE THREAD

**Issue by Jelly9912** [ImagicalCorp/PocketMine-0.13.0#13]
I can't join on server with file from releases folder. I see red light and 0.11.0 '~'

**Comment by Jelly9912** [comment]
For what build is this file ?

**Comment by legoboy0215** [comment]
OMG that is outdated. Check out the compiler or wait for me :)

**Comment by Jelly9912** [comment]
Ok :)

**Comment by astersx** [comment]
Just now i download and is 0.11 version =))))!!!!  Is this a joke?  :(

**Comment by Driesboy** [comment]
i dont have this problem

**Comment by keithkfng** [comment]
It will probably say 0.11. Ignore that, and try joining. It should work now.

**Comment by keithkfng** [comment]
If that doesn't work, try compiling the src folder yourself into a phar, then retry. If it doesn't work, open an issue here and we'll be glad to help you out.
