### ISSUE TITLE
Crops don't grow. 

### ISSUE THREAD

**Issue by KingDeadKnight** [ImagicalCorp/PocketMine-0.13.0#134]
My players makes some crops but they don't grew even if I stay 2hours there. For melon and pumpkin seed,  we put bone meal on them but no melon or pumpkin spawn. Problem for sapling too,  they don't grew without bone meal

**Comment by thebigsmileXD** [comment]
You turned it off in the pocketmine.yml

**Comment by KingDeadKnight** [comment]
Which line so?  In YAML file?
