### ISSUE TITLE
Class pocketmine\network\protocol\TileEventPacket not found

### ISSUE THREAD

**Issue by kniffo80** [ImagicalCorp/PocketMine-0.13.0#137]
Sometimes, with latest sources, the server suddenly stops with the following error:

Stopped interface pocketmine\network\RakLibInterface due to Class pocketmine\network\protocol\TileEventPacket not found

I took a look into the code and i cannot find that php class anywhere. This happens only from time to time. Any solution?

**Comment by Subtleoliver** [comment]
It's a railing problem since they changed tile event to block tile event.

**Comment by thebigsmileXD** [comment]
I think we have to change Raklib. I hope that we just have to fix the class bug ;(

Please go into config and set error reporting level to "2", then we might get more information

**Comment by kniffo80** [comment]
Okay - will do so @smile. Will report back later!

**Comment by thebigsmileXD** [comment]
NEVER. CALL. ME. SMILE!

**Comment by MCPEPIG** [comment]
This will be easy to fix.

**Comment by kniffo80** [comment]
I hope so ;)

**Comment by MCPEPIG** [comment]
fixed
