### ISSUE TITLE
furnace crash

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalCorp/PocketMine-0.13.0#138]
When i click on furnace in survival mode minecraft crashes.

**Comment by thebigsmileXD** [comment]
Haha lol. Victim. We'll have a look

**Comment by MasterWolf** [comment]
It was all ok with furnace in build #144 but now it is crashing again.

**Comment by Driesboy** [comment]
i have fix it normally

**Comment by MasterWolf** [comment]
Thanks! When next release?

**Comment by Driesboy** [comment]
i dont no

**Comment by MasterWolf** [comment]
Done! Now furnace should not crash :)

**Comment by Driesboy** [comment]
ok thx @driesboy
