### ISSUE TITLE
A little help please?

### ISSUE THREAD

**Issue by Rodrigo294X** [ImagicalCorp/PocketMine-0.13.0#143]
I have minecraft win10 on my notebook , but I can not connect to my server that is hosted in the same notebook. Can anyone help me?

**Comment by DRedDogPE** [comment]
There are some weird issues with localhost servers, happens to me too.

**Comment by Driesboy** [comment]
use the local ip

**Comment by Rodrigo294X** [comment]
my local ip is 192.168.2.101 but I've tested it and not work

**Comment by Driesboy** [comment]
HMMMMMM.....

**Comment by SkygridRex** [comment]
try putting this address 127.0.0.1

**Comment by GamerXzavier** [comment]
see your port

**Comment by Rodrigo294X** [comment]
I tried 127.0.0.1 but not work :(
My server is set up on port 19133 and is the same that I put in minecraft

**Comment by PEMapModder** [comment]
Can you see it on local LAN like another MCPE is running?

**Comment by Rodrigo294X** [comment]
I think I will have to continue using a second PC to test my server. Thanks to everyone who tried to help .
