### ISSUE TITLE
Areas of map missing in Build 215

### ISSUE THREAD

**Issue by MarcPow** [ImagicalCorp/PocketMine-0.13.0#146]
Portions of an underground structure that are present in the prior release are missing in 215.   It actually blocks out an entire, irregularly shaped area of the the map (above the area and into the sky) as unreachable, into which you can neither see nor move.

Reverting to the prior build renders the area visible again.

I don't have time to attach the map and area specifications at the moment, but I wanted to file the issue so this gets tracked.

**Comment by legoboy0215** [comment]
Hm... Typical chunk loading problem.

**Comment by MarcPow** [comment]
Sorry, I'm not sure I understand the state of this issue.   How can I help to get it resolved?

**Comment by MarcPow** [comment]
This issue is still present in build 323.

PowerPocketMine.CloudApp.Net:19132
World (newworld),
Position (-187,70,686)
