### ISSUE TITLE
isEatable not implemented.

### ISSUE THREAD

**Issue by kam187** [ImagicalCorp/PocketMine-0.13.0#147]
Whoever added the new items forgot to implement isEatable for them!  I'm confused don't you actually run the new code to check there's no console errors at the least? :/

"Fatal error: Class pocketmine\item\CookedFish contains 1 abstract method and must therefore be declared abstract or implement the remaining methods"

**Comment by thebigsmileXD** [comment]
It does actually nothing, i added instanceof food. Bit maybe i remove that functuin isEatable again..
Food is always eatable, nor?

**Comment by kam187** [comment]
Once you add implements food you need to implement all abstract methods
too.  You can just put a dummy is eatable in there that does nothing if you
want, but should probably do it properly and return true/false.

**Comment by thebigsmileXD** [comment]
Yea.. In 1 commit i said "can someone continue?" Because i was on school and we wrote a test there



> Am 26.11.2015 um 22:14 schrieb kam187 <notifications@github.com>:
> 
> Once you add implements food you need to implement all abstract methods
> too. You can just put a dummy is eatable in there that does nothing if you
> want, but should probably do it properly and return true/false.
>

**Comment by MCPEPIG** [comment]
Fixed by @mwvent

**Comment by thebigsmileXD** [comment]
Thanks @mwvent
