### ISSUE TITLE
Inventory Bug 2

### ISSUE THREAD

**Issue by DiamondShard03** [ImagicalCorp/PocketMine-0.13.0#148]
In a server crash, I rejoined the server to find that my inventory wasn't working. And by this I mean, it could open up my inventory, but the menue showed just gray, with no blocks selection. However the blocks in ky hotbar were completely useable. I was unable to use any other blocks then what I had in my hotbar. (NOTE: closing the inventory and reopening it had the same result. And this screenshot was taken of ONE of the inventory menues. The same thing showed up for all 4 menues)

![screenshot_2015-11-26-19-11-23](https://cloud.githubusercontent.com/assets/16039946/11432262/2d3f8588-9478-11e5-9a84-3dbca061ff65.png)

**Comment by keithkfng** [comment]
Which build?

**Comment by DiamondShard03** [comment]
Id what a build is... but if it means version, it was a 13.0 server

**Comment by MCPEPIG** [comment]
I think it's when a player in creative try's to join before the server finishes loading... When you relog it's back to normal. (It happened to me before when I join a bit before server finished loading)

**Comment by NML32** [comment]
This happened on my test server and you may want to disregard this report since the build I am using is based off a compiled build sometime after build #215.

**Comment by NML32** [comment]
I think DiamondShard03's mcpe crashed and when she came back her inventory was empty then when she came back the inventory was back to normal.

**Comment by DiamondShard03** [comment]
Oops... accidentally closed it. Sorry. (New here... XD)

**Comment by thebigsmileXD** [comment]
The server should block players to join when the server isnt loaded yet. Like on 0.11

**Comment by keithkfng** [comment]
Dunno how to implement that. And @PEMapModder is closing down on us like mad. Telling us to develop on a fork of PocketMine. Raging at us.

**Comment by PEMapModder** [comment]
Raging?

**Comment by keithkfng** [comment]
@keithkfng a bit exaggerated I have to say lel

**Comment by legoboy0215** [comment]
IDK how to use Git. Someone help?

**Comment by ZombiePower** [comment]
Works
