### ISSUE TITLE
crash on putting trapped chest

### ISSUE THREAD

**Issue by da123rrell** [ImagicalCorp/PocketMine-0.13.0#164]
server crashed don the latest GitHub build that I compiled

PocketMine-MP Crash Dump Fri Nov 27 18:53:21 ALMT 2015

Error: Undefined class constant 'TRAPPED_CHEST'
File: /src/pocketmine/block/TrappedChest
Line: 101
Type: E_ERROR

Code:
[92] 					$chest = $tile;
[93] 					break;
[94] 				}
[95] 			}
[96] 		}
[97] 
[98] 		$this->getLevel()->setBlock($block, $this, true, true);
[99] 		$nbt = new Compound("", [
[100] 			new Enum("Items", []),
[101] 			new String("id", Tile::TRAPPED_CHEST),
[102] 			new Int("x", $this->x),
[103] 			new Int("y", $this->y),
[104] 			new Int("z", $this->z)
[105] 		]);
[106] 		$nbt->Items->setTagType(NBT::TAG_Compound);
[107] 
[108] 		if($item->hasCustomName()){
[109] 			$nbt->CustomName = new String("CustomName", $item->getCustomName());
[110] 		}
[111] 

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/level/Level(1766): pocketmine\block\TrappedChest->place(boolean)
#2 /src/pocketmine/Player(1995): pocketmine\level\Level->useItemOn(boolean)
#3 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket(boolean)
#4 /src/raklib/server/ServerHandler(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#5 /src/pocketmine/network/RakLibInterface(81): raklib\server\ServerHandler->handlePacket(boolean)
#6 /src/pocketmine/network/Network(159): pocketmine\network\RakLibInterface->process(boolean)
#7 /src/pocketmine/Server(2489): pocketmine\network\Network->processInterfaces(boolean)
#8 /src/pocketmine/Server(2223): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(2101): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(1702): pocketmine\Server->start(boolean)
#11 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(boolean)
#12 /src/pocketmine/PocketMine(0): {main}(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT DESKTOP-VKAQ0JM 6.2 build 9200 (Windows 8 Business Edition) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

**Comment by Driesboy** [comment]
Ok i search for a fix

**Comment by MCPEPIG** [comment]
Is this the redstone branch?

**Comment by MCPEPIG** [comment]
or master?

**Comment by MCPEPIG** [comment]
Nvm.

**Comment by MCPEPIG** [comment]
Nvm.

**Comment by MCPEPIG** [comment]
Fixed.
