### ISSUE TITLE
#215 not loading plugins.  None of them.

### ISSUE THREAD

**Issue by edgararroyo** [ImagicalCorp/PocketMine-0.13.0#167]
Coming from #197 I tried #215 and loading was instantly stopped when loading plugins.  Do plugins need update?  #197 which is 0.13.0 allowed plugins..

**Comment by Taki21** [comment]
Are you talking about a phar error? ERROR: Cannot retrieve contents frm "plugin.yml"? That one?

**Comment by Driesboy** [comment]
I dont have that problem

**Comment by Taki21** [comment]
I fixed my problem

**Comment by Taki21** [comment]
I had to reset my Computer to fix the Plugin loading? xD

**Comment by Driesboy** [comment]
Close the tread please

**Comment by Taki21** [comment]
Me? I was talking to @edgararroyo Lol

**Comment by Driesboy** [comment]
Oops sorry

**Comment by Taki21** [comment]
no problem

**Comment by edgararroyo** [comment]
LOL...  EPIC.    I rebooted the server and it started working.  I hope they get all these issues resolved with PHP....  I know running multiple servers I have to start them manually, they don't always load up.   Sometimes it's a segmentation fault, others is error 127, others cannot bind to whatever whatever...  And the funny thing is it's just starting them!  Not even using them.
