### ISSUE TITLE
I can not open the furnace in build #215

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/PocketMine-0.13.0#171]
I can not open the furnace in build #215. When I try to open, Minecraft (not server) crash. Please fix

**Comment by alex2534alex** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/issues/163

**Comment by keithkfng** [comment]
Please stop submitting duplicate issues that we already know about.

**Comment by alex2534alex** [comment]
Ok

**Comment by alex2534alex** [comment]
You know about red stone?

**Comment by alex2534alex** [comment]
Know?

**Comment by thebigsmileXD** [comment]
THERES ANOTHER ISSUE FOR THIS! Please never ever ask about things that are in another issue already in issues that have nothing to do with this!
