### ISSUE TITLE
I can't break red stone and any kind of stairs (build #215)

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/PocketMine-0.13.0#172]
I can't break red stone and any kind of stairs . Please fix

**Comment by Driesboy** [comment]
Ok tnx for posting

**Comment by keithkfng** [comment]
@Driesboy you act like a team member. But you're not XD

**Comment by Driesboy** [comment]
:(

**Comment by alex2534alex** [comment]
Hm, can I ask you: which patches have been applied in build #294?

**Comment by alex2534alex** [comment]
@keithkfng keithkfng, ↑

**Comment by keithkfng** [comment]
Chest patches, and experimental crafting patches.

**Comment by robske110** [comment]
Why closing this?

**Comment by keithkfng** [comment]
This was fixed.

**Comment by alex2534alex** [comment]
Ok
