### ISSUE TITLE
Trapped chest open crash

### ISSUE THREAD

**Issue by andris155** [ImagicalCorp/PocketMine-0.13.0#176]
PocketMine-MP Crash Dump Sun Nov 29 11:20:31 GMT 2015

Error: Call to a member function getInventory() on null
File: /src/pocketmine/block/TrappedChest
Line: 170
Type: E_ERROR

Code:
[161] 			if(isset($chest->namedtag->Lock) and $chest->namedtag->Lock instanceof String){
[162] 				if($chest->namedtag->Lock->getValue() !== $item->getCustomName()){
[163] 					return true;
[164] 				}
[165] 			}
[166] 
[167] 			if($player->isCreative()){
[168] 				return true;
[169] 			}
[170] 			$player->addWindow($chest->getInventory());
[171] 		}
[172] 
[173] 		return true;
[174] 	}
[175] 
[176] 	public function getDrops(Item $item){
[177] 		return [
[178] 			[$this->id, 0, 1],
[179] 		];
[180] 	}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux pe.infinityhosting.hu 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
BanItem 2.1 by LDX for API(s) 1.0.0
Slapper 1.2.7 by jojoe77777 for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SimpleGamemode 1.0 by MamayAdesu for API(s) 1.2.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
SimpleAuth 1.8.1 by PocketMine Team, shoghicp, ecoron for API(s) 1.13.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwlvGzmW/itcOcDYC5Xuw1bDAbyO05OFk3giZ7LYVCOgqlgS46pidZFlWWnkv897j6xLdnec
xAvMOt2weD2+43sHSfmPjpGJ6CyGk8nx/GQ2GA+7HZHnKu8s/uiYXQZDnYtPF+/evX3X6XYSoTVf
Y985j2NmFOMsEclK5Cwq0sBIlbK1MK/SW5Eale8Ojxj0pEUcw+JIxriyr/Ogn6ngRphEpqK/iuFz
/zrnWSbC843QBubGMAJMzQdfu50sLtYy7SwiHmvR7QQqFMjccDYEar7BfzI6lFoLc/gsQALe85Qn
IjR87T2/BOpHjKche3iMyVQbngZCRWxpcpmuj/4ABoazUUWd6D+82nsO4v6Tx4UAUf/j9JQ9k0Yk
1HteaKOSNzD98MiRHDdI+iYXpshTZvJC/ELDk8bwV+qZVj22PYM2fZg3RX+WxXwncu+51Oe54Ebe
1lseN2je2/CkTX4+qNoVSR6GH2Qaqm2lgLZ9j4jSvDSFpTNybM5Lgfd3nltR7expOXtGnVmximXQ
wtOLXGX68BVo1urXyjaft6l/pM5a4I/PzEZq0ErYZYMuG/7WpQml0L8RJ8cDxwkAzeQ8AGh97BwM
2OHRgtUg9f2lyG9RH0HO9eZFkWSHK6ViwdOjDtBdi1TkPEZYwiwNbAPVYW8WilvYZFXIOOwsBgDl
XBkVKJg4Pu52eCZp2nDcG8C0tTTQHDzyBxbk/CaWK1zTmxOFAsEJ7UuZFncsEz2ZRjKVZrdR2gCy
e5uCjXvDSW888u7gx1vn2pPZ7cybTdjBlC1fX7EPImRLkbETNpwvRpPFeMLOL5bXbDQYTtnd8ewT
wBQE2WSwz7Q3642g9UWkIF9nBM2BHfykdMkHdFAjpkblzxqVdVXk4krkCTUc83Vft6XMEW3FC7NR
uUYrzSYvX4IefnOK/IiaHPWoQ6R8FQvgCRHX7YQiAw5xEYxpFZkXzY6EY3TpfLL0fL9ioPERQ5Li
KOTy+uzd9fsr6NiKlQY0Qt/GmEwv+n2w4KZY9QKV9GmlFbRfUwHplzLJYvHaBtKm3HsDDeFB9pbg
LwqjblpyD35c7Pa2APR9NpzcV2+X1x/evrt80ZQcIzvIdBGoVCW7s6tXDXkanU1DgoV6J21DqlSs
4P97EnXRou73qPo9pN9j1x679sS1J9D+QU04NnxfWM6BF99vSfEIVfyvzKzZL2GuyBv62B9poxsk
aSuFx7KId210/4SZ93b3/dfY/72o5rH4DKk0V8BcI4d7zqX7EIpFP+HaiLy/L2+Nk6WI4/tAod59
pMy/jZRv+nwTid9hfg38VPZ3zD0CAPIKYrwIjGravtHZlBDAy9sCXr74n5ZwJz9ucSDl+/XG+xZ/
UIaHbA50vNfnVxf9hhAg5/mGm3OR6pacjc42vCdtMS9uVbwEvp9K1nrf7wH2drvtCeAEqfbMTROh
G5U9gFDs/XdCKPBTI9Qy9wiEXsoEmmFZKjbk3B9p29CG5IasK66hoMF9nypKVRR9/z4vf25RJ9h/
8RRrxIZAZU/baMO/9rnBT/qc2/RRDuc4X8Z4+ml6UtmzXwPtwe2z+qzEHH+erA7SdmffTx7N/mu+
lsG1iMWVyg1vxvb9kbY44/2S7omTniUHkpjse6zhPOq/1ep+DMDO/RAw+X9RznxWqypYWCkeA0yq
Bn8FFSTu2N2qVquBvUjRVshrnvDdWSh00dLJT2A0QYocKfq+Jk7WjpP99uPEfKP+qWTYEM91NMQa
9MYtoXKZSwP/nip0lPR83+79PYClWxO8jhDtZFz37oWRR2Tj45/JxtXGT5OOL3ka3ndF6v2Bo8X/
VTqOgZ/Kwxxzjwme57/OZ58+qDwOL0K8AqiD595IU9ZBb7pvRqzEg5xHZi1SWej57KnsmQTr+cz3
bZHv+1tkSABDvl/xhpX+q/R7YsoZMH4vnlBnG6vH++n6io4dr0FYdi045naog9YbGWD5A6bIYWHL
3OOfPRwjV+XB2HH4nZcBFcv9BhV03Fjw/JKv1023rfr2T4h7YfVSgKHDtxEW508VharNoQArj6nf
fWBo8NWvpWlZ/u8i3qt39oe+kWQfqhS+6dcN5T+iatgQIz98bvqes/I96UFZeGuE55q9qzHq2i+j
xt++GRt+Szn1LdU93XRecrqL1XAC7PzJjRnyVX/66fsyIoIZQGuRGsljDSBvpIBm9zduUiwetQWk
jRlPVSs32Xgqj2mJ9hXvS3kOQgNMSmboKroHByVAipF4idg5uKpa7FylkVwzfG7xcz89WBYpe6Nu
2eiEDYeL4XwxPmG/vrY3ujghUSY89YvBgM+P7a/Y87yP9mNwvRFv45DZVuS5D/wcEw2w5NpjkL9F
4TcggcQts14G5f/p8GQ4HmHndgOq8GKpzekA2zxNVZEG6Bv06sCDjRS3IgE96FOVEp2Mb1MvszcQ
YOrTIbHO79wafTq2pOJYbb0oluuNaS3lqUxAp62+RK3KjrJetAxFKgduqj4VRdi74XkI+aVqZ7eZ
Wx3KKJJBEZvdKQlo3wOMyj0tDN6861PsjkGo2EMIn1ISrfu0EGFjCj68nb64eHn2/vIaey02vd8L
ke/clq4rh3Kj5Ac/9zKuNRAPT/+TfkAjhVGe5reiFN1aRGanU6gEp3DCOIYcOxjj2K0UWy+U9kHs
dIZdeJ9fBa/eLokRbQxjIgsIaAUIiu80iDcGimN1tvNeXwH+GEBIC1ZqgvFcMLMRDGonDR+4YQEC
wLCVYDIN4gKKC/jA7uEcaS1VAisjJLBPU/NIdJmCEYAlkGSrXPAbtlNF7mgxGTEwqIwk7QC2zAFN
EOuB8Buxrcj1QxFxsKZmW5X+zTA8EPOcoSYTEDYAkO3wYRPfl6zc241IWZGtcx7iO4ufop4tsYWf
soPrDUR7L4Yu4AIKxXXB14LhUyapzNlES2jHCujLL6RUXArVdOCkaC8EBspYItLeVt7IDKoy3lP5
uo+t/iUY8pOKPr1avv00G594o0+4DtRYEVowH+Le2u/gRh82AnWHr7oQgUKGL7yaXkTBTDlPdcwN
6I2GSZvEKfABn4Qhk4biVgaCbSDvxWTkBAhbZ6q3pHdc6NebwoQK3dA+NiAzZ0x/IeIGaGIoEcM4
pt+hUcbYnpseO1zaaRR+Iv45BzyGbp6dpI+sVGcYEBjGGhCEueTLbiVn/0BvginkVWVartk7WG5g
IUeUawXSOC6tqbmjxAoNIIZcAUAi7cCZAWZC7glRz/WAB8yulAYhMb0g+Qty4JIOPlBjbGEAd0AU
8rraMYdDmO7cvRpt8PlBgqFUCpDkYchyOBQTcpFNwOoNsMM1ZFSMpgzwuhKoEDCa+L3g9Ia/lrcw
9xZfsdmh2xKywxEQt/tBmBEYwT1Aw3ot8gWM4s5vCnr6B3c807s0uOb6Bjwmh3Of7uH4ew0aQXyX
QuKsDRToqgBIwWzdZRQImQuYAPkuqCEBrWlM6KQWSJ3YlxQpeB5OIdpLghzIA86ZqzsI7kaACkAc
cpW0Yg21atl5FaGH07cWwJO7TJq/4ZcYcloVCswshOK9tewQJAA7sxFqhGTwnJQLooTejpki35Gv
/xqrFSgWawZmuwF+iTQY0xKx5qudAYbY0rIyoM2lRvPaSAEybSUxRspmmNAsnVL/mvQSSYALhDmB
j/FIJYIYU+5ozQ/CFATatQI5FDoM6gz2WROTHjG2YAOfQg1FdQOhiof/5uxj/fUXzGOm/inmtVEZ
7e9CXcWPo6YZuBSmWhGW3OCeeyxBOS0V5TJ0RI27BRTNHWuVsw1hH4gzIQKMZnjgDMK6GeUABRVh
Cu4JSsPQ8Gc6tbqE8iqm9ICObqf5lK2RBrhe7cY2FuEObzF+YHqk6b37k1FmVyKD/jIRYBbVpBPk
1SrYrq0EADWKTNdijgdOTn30IENO6rGVes3zFRjfC1Qc26IP3etBrRKWkBW3hrk14LgJTwvK100u
oJYpAAhH3TIg7CHBQcEG1SgqA0NSQ6zH3tpkSS2Aw0YVcVgxIiF8bFNWs46gZRlxDgLOBgMrIzt4
SW5wLzASVuzqSqgoV0kZX3GtG/eaIalhUxDCmW4fCg/gp7EOi+pgU6Q32uqbXmIoGlIncoYHHJSG
2eK7S76ZQ/Wi7SQPCwgshGpaSKo0s/OSk5nj84Wyy/bNhxkAyyy7rEnB7uKmPYHMlIW8gON3nEhq
h4VyIxyoUvdfkvLTVBi0RVX3ATRimwZX3MDJBssQjiUyZD/AkwtJ5IC2qnWjNhKtRJUQKdYcNGNX
OYKOn+8M0u4yb9gAMyY+2tYzJSsQVqYzG1XqREvnDsxyoY11zoB2LXQ6nnrs73CyAvWeQiENwD2/
et+FtcDBCuLPVoZmY0M2+XdF3iPyCzZ3VUFdL2hSTGNqj52F4E8bHkd9OCHYEiYUgDO3EWxp8afS
pkNWqblBq1EkXdyh82ENxOOudWzc2H63DcQC2AiCNib691fpVVkm1AU/VkC4aAuB3sdqP80812wW
ZHAaFKtivXAVx3M2xErDpRUsKWm4LCc1xbGNKMtM35liwYZ1kahZH45kpgDA9NeBVS3EtVA3Ni3P
ka1DhygrSOQbJLHHLZrq4IXiksEDfGglhLklnl2yYAkMrd1hBASi6xFkF6t0bYMSb9GHyInHOdPY
HpRp7nNDPkqmO3jz9vpiwSjqwn9BASezFE5mRIgux9B0xJ7buWKvMvFZy1oBHEIgkjhZCUWUkoAT
RI1B5IwGLoVgKLOZCWGEB2bsd+nIeX27u4xhthBeoruigCuuRWOzwyE4ygO7dNkIBoYPDQgT9I7I
abVockFwuEbKeC5zlx5MQGCy+2Hqt5akE3B9NMZAQGcgLJ0wHPB4y3fa0nZ0GjhqxW+C0VmiirSZ
ALQr2EomkH2khucFiM34ccEmf76U59AbWt4tjXbWYcOT0YOrCV2psIfQlbDUViLCSEQ3Ohix0AwV
VXvP0wh9NvIt+S0kXSzuJJ61BZ69sp27V3C5qCpoKFBEdFFbhkUXxqIipmlKA1Q9dFEZ2FRC568c
D/MADCBbquqzwmOQ9Q3NE8RKQrESE0wl/54xUKGlMV7zO8b39QIHoIDyQ42Hti0IpO94KAvdWObs
wB135KR2qcMdzodqBWMS3qd5RRYCFhtn5ABv9y2S8IRdZ0HLeH2qK3nv3Wfexb8tl3RCh9N4IZx9
3Xpye+r3NBhrwY5/iFqmsiJ21NxnTE17hP2UfNID7SHT9trQIxxp1CSqMoFYbfC+xvUOXXjAW7YF
s8VdaVL8jnCRQbFjKz4LSAoettBwtIDKHFe5DZHoFJtbjhtVndTHk5UE5Nsp7oLPHtAXNhjhXQJ+
T5nZXptjHUgsel0lXwU3xLWHt0PtniqdtHqzTSbTSNUwwK8XL+yWvcZlIRRCxF+q0l2CZT55iAb9
6opRPLe4YVYPE8OANc74eg3Zx90MVHcuWCPit7Vv9qRpM4T09EMMocIslsnG95YDKuzwwpogTz2X
nusakHpVVqvm4ByvHOkOTMQqw3zVhTbIgBd8pizGoDaJoFYWoG7IUClmepzkkmuB9gGPbBBh7nGj
UUUUUHJqY1NcGfIcNbSRHS7p1xxareAz+wM6iSUkHGuXizuOGdc2sGQB+o6JRckNailrttLiRjTb
62TB2l8SWawT3MnGx7JAaV7iknDlScIe58p7dDqnPXQnTMdeym+aaglURwIlhoSNXfJviES7EgP0
ieG1Ozo1Jat6twV7eXl2vRj9Mu9OT+6G3fHduDv6ZfhLiM/LhMVDfL0LMPacHg/YGpCvbWsyPcJn
6DsjUlQEfcH7HPJT49vyCKxGE9LEuvrjlizAqa6hf4+lEWP7BX/P/i3BF/uNf/v9oVUA9c6m/ssY
HoNH8bzusH/AU7aKPK4akYwNPsAC6aF9WY5MVo2uk/rzBry6+lbPZ119Ew2f5ZOVvSCuJkOtuMtM
LYHhyFDYEHd5dUm74ucsgBqvXrsDgekPCdwnNu0hdyg58/C5ajSYDsbw8dkrdNbxfCz4NAyn0/Hx
fDacDGb8eDAa8cnqmI/nk8nweDWaDAR7BjtdbVAt9JBMGyst72qlu0O8mzBEQd+JyJ1AoZf2OxbT
KOBQwU5g20E0nwfz4+PZdApbj09GYzEerE7mJ2FI++lNomoVanI33ZZUWuXDZKNuRAr5J696Pgh+
A3HCKqo3hZ4dp5cXfN7ECV9kZluj3qTz9eu/AFE+NTs=
===END CRASH DUMP===

**Comment by keithkfng** [comment]
Trapped chests aren't even implemented.

**Comment by thebigsmileXD** [comment]
But... If they would, then the bug is on getCusromName

**Comment by robske110** [comment]
Why closing this issue?
It is an issue, the trappes chests aren't implemented so why closing?

**Comment by keithkfng** [comment]
Then why don't you try fixing it? This isn't a priority.

**Comment by thebigsmileXD** [comment]
Its the redstone branch. I'll bring out a temporary fix.

**Comment by keithkfng** [comment]
We can merge the redstone branch without using git bash. I can't be bothered to use it, I'm soo tired. @thebigsmileXD can you try if you have some spare time? Thanks!

**Comment by keithkfng** [comment]
*cant* not can

**Comment by thebigsmileXD** [comment]
Its fixed.
What is git bash?
And i wouldn't merge it. Too buggy yet

**Comment by andris155** [comment]
Temp fix: Use Banitem plugin /item ban 146

**Comment by thebigsmileXD** [comment]
How powerful this delete symbol is. You can remove pointless comments with ease.
