### ISSUE TITLE
MultiCraft support

### ISSUE THREAD

**Issue by andris155** [ImagicalCorp/PocketMine-0.13.0#178]
MultiCraft players list
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11459702/06ab7f0a-96dd-11e5-8142-ab65fe760bae.PNG)
Connected players list
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11459738/c87cbee6-96dd-11e5-94cf-4fe33a2dafea.PNG)

New Pocketmine join format not support multicraft.
[Connect] User Replay85[/XX.XXX.XXX.XXX:19132], IP 
[Server] INFO Replay85 joined the game

**Comment by keithkfng** [comment]
We don't provide support for MutltiCraft. Sorry.

**Comment by robske110** [comment]
Those messages should be realy easy to change

**Comment by andris155** [comment]
How do I change it?
