### ISSUE TITLE
Creative Mode Inventory Bug

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/PocketMine-0.13.0#18]
Not able to place anything in the hot bar while in creative mode.

**Comment by mwvent** [comment]
Confirmed

**Comment by keithkfng** [comment]
I believe this is a packet problem.

**Comment by NML32** [comment]
I remember seeing a similar issue with PM 1.6 (0.12)

**Comment by keithkfng** [comment]
Yes, in one of the builds.

**Comment by thebigsmileXD** [comment]
Assigned nothing to me. I have other things to do and won't work on the PocketMine-MP 1.7 anymore

**Comment by mwvent** [comment]
was this it?
https://github.com/PocketMine/PocketMine-MP/commit/24f8de2cc3a82c6651b93040f2a1e8d04961d977

**Comment by mwvent** [comment]
I copied that version of PlayerInventory.php and have some progress. I can put creative items in my hotbar now but get some glitches where the items changes rapidly between other items sometimes.

**Comment by EpicSteve33** [comment]
Please fix soon lol

**Comment by keithkfng** [comment]
I will try and copy that and see how we go. Thanks for the suggestion.

**Comment by EpicSteve33** [comment]
I'll test it just tell me when

**Comment by keithkfng** [comment]
Done. Compile the src folder, then test it. The inventory should be fixed.

**Comment by EpicSteve33** [comment]
It works but 0.13 new items can be used

**Comment by keithkfng** [comment]
Wait... What? That's awesome!

**Comment by EpicSteve33** [comment]
Ya it worked is there anyway to make Redstone work?

**Comment by keithkfng** [comment]
No, sorry. Something @shoghicp will have to implement.

**Comment by EpicSteve33** [comment]
Ok

**Comment by thebigsmileXD** [comment]
@mwvent nice :D

**Comment by mwvent** [comment]
Ta much :-)

**Comment by reidq7** [comment]
Is this implemented in 39?

**Comment by keithkfng** [comment]
It was fixed in #59. Wait for the latest release with the world bug fix.

**Comment by reidq7** [comment]
Sounds good thanks dude
