### ISSUE TITLE
Anvil and quartz pillar rotation

### ISSUE THREAD

**Issue by Rodrigo294X** [ImagicalCorp/PocketMine-0.13.0#181]
Also noticed something with the pilar quartz block, it not stand horizontal, just stand in vertical

**Comment by thebigsmileXD** [comment]
Do quartz pillars finally work in singleplayer?

**Comment by InfornoFire** [comment]
ok quartz pillar was never implemented to do that just yet, anvils also was never able to do that, the way the type of blocks have to work is sorta easy to code in, you have to copy some wood log file data. I say it could be done soon

**Comment by thebigsmileXD** [comment]
Again: Does the CLIENT support the quartz pillar rotation? It didn't in 0.11 and it was reported many times to mojang
If so, it will be easy to implement

**Comment by Rodrigo294X** [comment]
Yes. client support the quartz pillar rotation!!

**Comment by thebigsmileXD** [comment]
Then i'll do this. Anvils can rotate also?

**Comment by Rodrigo294X** [comment]
Anvil rotate in singleplayer but not in pocketmine (like the pillars)

**Comment by InfornoFire** [comment]
ok, case close this issue will stay for a bit till it is fixed

**Comment by thebigsmileXD** [comment]
Quartz pillars fixed. Anvils will take some time.

**Comment by Skull3x** [comment]
Fuck you I don't want your shitty plugins anymore.

**Comment by thebigsmileXD** [comment]
Sorry, what? They both have been fixed! And keep calm!



> Am 02.12.2015 um 01:02 schrieb Skull3x <notifications@github.com>:
> 
> Fuck you I don't want your shitty plugins anymore.

**Comment by keithkfng** [comment]
@Skull3x shut up, and get outta here. Never come back again. GET OUT.

**Comment by thebigsmileXD** [comment]
I am almost sure that wasn't actually him but someone having access to his device

**Comment by keithkfng** [comment]
I am sure he meant it. It's normal for him to be like that I guess. Insultive.
