### ISSUE TITLE
Build 320 Hotbar bug 

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/PocketMine-0.13.0#182]
Shovel rotating/rolling in Hotbar slot.
Tested in creative mode

**Comment by keithkfng** [comment]
Known issue already, thanks for reporting.

**Comment by MCPEPIG** [comment]
I think someone uploaded the wrong phar. When I used it, same thing happened, but when I downloaded the zip and used it, it was working.

**Comment by keithkfng** [comment]
I'll recompile it later.

**Comment by thebigsmileXD** [comment]
Isn't already 323 out? I was sure i uploaded it
