### ISSUE TITLE
Error eating...

### ISSUE THREAD

**Issue by legoboy0215** [ImagicalCorp/PocketMine-0.13.0#183]
I get this when I eat:
[CRITICAL]: Could not tick level "spawn": Value 22 exceeds the range!

**Comment by deotern** [comment]
Okay, most likely this is my hunger code issue... zzz

**Comment by deotern** [comment]
Does it crash? Can u eat? Or u can't even eat?

**Comment by thebigsmileXD** [comment]
Oh.. i see. You have 20 food, but your saturation is everything after that.

**Comment by deotern** [comment]
@thebigsmileXD I don't understand what you mean... can u explain it to me? xD So, I can fix it

**Comment by legoboy0215** [comment]
You can eat, but after that your item does not get removed and no hunger comes back. On the console you get a RakLib 5 sec and world error.

**Comment by deotern** [comment]
I fixed it :) Creating new build and merging commit right now ;)

**Comment by keithkfng** [comment]
Since when did we have a Fixed label... LOL

**Comment by deotern** [comment]
I just added it LOL

**Comment by thebigsmileXD** [comment]
@deotern Well.. food has a special amount of saturation. If you eat, that saturation is added to the hunger. The saturation points of a player can be more than 20, whatever amount they are, your client always only shows 20 or less.
Understood? Idk if i explained well..

**Comment by deotern** [comment]
49c6e3c9c11f8d03da2f17a55aa9a1e2b8fe6d09
