### ISSUE TITLE
Cancel sprint when hungry

### ISSUE THREAD

**Issue by KingDeadKnight** [ImagicalCorp/PocketMine-0.13.0#184]
How about the slowness III? I get it when I'm out of food, I think. I'll look better at this "bug" in few hours and update this issues when I know more about this.

**Comment by thebigsmileXD** [comment]
Nope. Sprinting is cancelled then, but you don't get slowness

**Comment by EnderKenji** [comment]
And the latest ver have a bug. Doesnt show 'respawn' page after dead. Please fix ASAP.

**Comment by KingDeadKnight** [comment]
So, to complete my issue, I make some tests. Then, I say with certitude that pocketmine gives us the effect slowness when we come under 6 points of food, you can come make test by yourself if you want. 
And maybe already fixed, we died from food in survival and creative gamemode.

**Comment by thebigsmileXD** [comment]
In the current code it actually gives slowness :fearful:
That would make you even slower when you walk..

**Comment by KingDeadKnight** [comment]
I know, do what you can do guys :)

**Comment by thebigsmileXD** [comment]
Yea.. :smile:

**Comment by InfornoFire** [comment]
In the latest dev build, it does give you slowness, but doesn't work, and sprint is cancelled

**Comment by EnderKenji** [comment]
No need slowness btw... .-. 
Or maybe u guys fix the effect... hope effect works well...

**Comment by deotern** [comment]
I fixed it :)

**Comment by keithkfng** [comment]
@deotern off topic check my reply on pm forums
