### ISSUE TITLE
Death Glitch

### ISSUE THREAD

**Issue by Skull3x** [ImagicalCorp/PocketMine-0.13.0#185]
When you die you can't move or respawn, the respawn menu us unavailable and you must rejoin to be as default, normal again

**Comment by robske110** [comment]
It works for me, using build #323!

**Comment by MasterWolf** [comment]
I can't respawn too. All is as said @Skull3x

**Comment by robske110** [comment]
![image](https://cloud.githubusercontent.com/assets/16020100/11507676/75c0da4c-9855-11e5-9b54-74a38fcee42a.png)
Still can't reproduce it (Build #323)

**Comment by robske110** [comment]
Have you tried to delete your player.dat?

**Comment by keithkfng** [comment]
That's an MCPE bug. Not a PocketMine bug. I don't think this can be fixed... Sorry.

**Comment by robske110** [comment]
So why is it not working for them, but for me?

**Comment by keithkfng** [comment]
Not sure. Somebody said on the forums it was because somebody had not killed you COMPLETELY, therefore the server didn't receive any data you were dead, so you couldn't respawn.

**Comment by robske110** [comment]
That would result out of packet loss

**Comment by robske110** [comment]
Ah! Just realized something! I did get that error suddenly, and said to my partner i can't respawn he said you are not dead, i looked on his screen and i was still there!
Then he tried to hit me, and he was able to hit me to ^death^ and then i could press respawn!
So the client thinks <I AM DEAD> and the server thinks <HE HAS 4 LIFE>...
ALSO THAT ISSUE was too in the offical bleeding builds from 0.12, so THIS IS NOT 0.13 fault, it was there since 0.12 and maybe even earlier!

**Comment by keithkfng** [comment]
Yep. I remember somebody saying the exact same thing.

**Comment by Skull3x** [comment]
I don't need ur fucking shit anymore,

**Comment by Skull3x** [comment]
I don't need it!!!! Fuck you!!!!

**Comment by Skull3x** [comment]
I don't need your shit.

**Comment by robske110** [comment]
Could someone ban @Skull3x ?

**Comment by JoshBlazed** [comment]
@Skull3x was hacked, he is innocent. If this happens to me then I know it was kieth... jerk leave Skull3x alone

**Comment by JoshBlazed** [comment]
Tbh he wasn't even in github, I wish you could check IP changes...

**Comment by JoshBlazed** [comment]
And I swear if it does happen to me I'm calling the police

**Comment by thebigsmileXD** [comment]
I knew it..

**Comment by Skull3x** [comment]
I don't really care anymore, but a second action by this "hacker" I'm also
calling the police...

**Comment by keithkfng** [comment]
Oh, so you think I hacked his account eh? Wow. I'm too unadvanced to be a hacker.

**Comment by JoshBlazed** [comment]
How am I supposed to know that

**Comment by JoshBlazed** [comment]
Plus "I DON'T NEED YOUR FUCKIN PLUGINS" it's not even a plugin...retard. It's a pocketmine un-official build. I'm sure skullex wouldn't be stupid enough to say that -_- *face palm* it's just common sense
