### ISSUE TITLE
Question: When weather will be added?

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalCorp/PocketMine-0.13.0#187]

**Comment by Taki21** [comment]
That is something that pocketmine should have added! It is already in Minecrat pe and should be easy to add! But guess what! Pocketmine didnt want to add weather! (Pocketmines Problem! Not Imagical Corp's)

**Comment by MCPEPIG** [comment]
It's so easy huh? Why don't you do it then?

**Comment by Taki21** [comment]
Edit: Easy for pocketmine to add.

**Comment by ZombiePower** [comment]
It is added, but not fully implemented.

**Comment by thebigsmileXD** [comment]
There are plugins for weather. I think thats fine.

**Comment by MCPEPIG** [comment]
@thebigsmileXD  Really? I haven't seen any plugins that add fully working weather.

**Comment by Driesboy** [comment]
My plugin snow

**Comment by thebigsmileXD** [comment]
Several can create snow andlightning bolts

**Comment by XiangZhao969** [comment]
But it's really buggy and in some cases, it makes the server crashes. Pocketmine had added that already, but there wasn't any commands or plugins to "remote" that.

**Comment by MasterWolf** [comment]
@Driesboy  please send me snow plugin.

**Comment by thebigsmileXD** [comment]
https://forums.pocketmine.net/threads/weather-in-pocketmine.12695/

**Comment by Driesboy** [comment]
https://github.com/GameCraftPE/Snow

**Comment by MasterWolf** [comment]
@Driesboy thank you very much! N
![screenshot_2015-12-02-18-52-22 1](https://cloud.githubusercontent.com/assets/15979343/11537854/cafc16e8-9927-11e5-98eb-d3088f441083.png)
ow i have snow on my server! It is AWESOME! THANK YOU!!!

**Comment by Driesboy** [comment]
i go make a rain plugin

**Comment by Taki21** [comment]
OMG Thanks @Driesboy !!!

**Comment by thebigsmileXD** [comment]
If its rain or if its snow depends on the biome

**Comment by keithkfng** [comment]
I like SnowHalation better. You can control everything.

**Comment by Taki21** [comment]
Link doesnt work?????!!!!

**Comment by keithkfng** [comment]
@Driesboy your message has been deleted. Don't advertise on here. Read the README file - this isn't a forum - this is an issue tracker. You're spamming my dashboard like crazy. One reason you're not in the team - so stop asking.

**Comment by keithkfng** [comment]
And just use plugins for now.
