### ISSUE TITLE
Craft

### ISSUE THREAD

**Issue by FunnyCrafteur** [ImagicalCorp/PocketMine-0.13.0#188]
Hi !

I can't craft (check my screen)
http://upload.hmsw.fr/uploads/9bf0be761b47134540b65a750e133b74img-3168.png

Thank
FunnyCrafteur

**Comment by Taki21** [comment]
I think i know how to fix! i'm making a pull request!

**Comment by ZombiePower** [comment]
Fixed

**Comment by ZombiePower** [comment]
Sorry just looked at the photo, I will have a look at the player crafting inventory

**Comment by FunnyCrafteur** [comment]
Fixed or no ?

**Comment by Taki21** [comment]
My pull request got closed but not accepted!

**Comment by keithkfng** [comment]
Yes, because it caused errors. That's how it works. If it doesn't pass, closed.

**Comment by Taki21** [comment]
I know now! lol

**Comment by keithkfng** [comment]
Fixed I think.

**Comment by thebigsmileXD** [comment]
Nope. Still cant craft in latest build win 10 edition

**Comment by deotern** [comment]
@thebigsmileXD Only happened in win 10 edition?

**Comment by thebigsmileXD** [comment]
I don't know. i still run 0.11 on my Smartphone
