### ISSUE TITLE
Make a file for ALL ABSOLUTELY localization

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/PocketMine-0.13.0#190]
for example, there is a file "eng.ini" in 'lang' folder. But it does not have all the words and sentences that are used in PocketMine. Because of this, ordinary users will have to review each file that would find the word that he wants to replace. So I ask to do a single file, which will contain all the words and sentences, and all scripts will apply to him. And it allows the average user to edit their own language to fit him needs)) If the language is not fully translated, the script will access the main language.

**Comment by robske110** [comment]
This is a job for shogipc and the other real pocketmine developers, not for this community developers, they must concentrate on fixing 0.13

**Comment by InfornoFire** [comment]
robske110, if this issue is for shogipc, dont put it here

**Comment by keithkfng** [comment]
He didn't. Please check your references first before posting.
