### ISSUE TITLE
Bugs, bugs, and more bugs

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalCorp/PocketMine-0.13.0#193]
golems will not spawn, spawners are broken, ban-ip somehow does not work, more will be added soon

**Comment by InfornoFire** [comment]
Hunger saturation is not working even on build 332, mobs do not move, golden apples do not work

**Comment by thebigsmileXD** [comment]
How many times do we have to say.. MOBS AREN'T IMPLEMENTED YET (atleast their AI)
So spawners are.
Golden apples will be fixed soon i guess. And saturation is in progress

**Comment by InfornoFire** [comment]
Ok ok ok, welp

**Comment by InfornoFire** [comment]
how bout the others

**Comment by thebigsmileXD** [comment]
Golems are Mobs. No AI.
So they don't spawn.
And as i said, hunger will be fixed

**Comment by thebigsmileXD** [comment]
Edit: ban-ip.. No idea.

**Comment by InfornoFire** [comment]
im gonna close

**Comment by InfornoFire** [comment]
even though 1 bug is officialy on the loose

**Comment by robske110** [comment]
Ban ip has THE HIGHEST PRIORITY, if it does realy not work I will try to test it

**Comment by thebigsmileXD** [comment]
You know how to use it, right? /ban-ip <ip>, not name.. Just saying, many people use it incorrectly

**Comment by Rodrigo294X** [comment]
But if I can not use /ban-ip name, how do you know the ip of the player who want to ban?

**Comment by keithkfng** [comment]
You don't use /ban-ip <name>. It was never implemented as far as I know.

**Comment by thebigsmileXD** [comment]
-.- e.g with the plugin iplogger. So you just were dumb and this isn't even a bug?

**Comment by thebigsmileXD** [comment]
It is
