### ISSUE TITLE
Help me MySQLi

### ISSUE THREAD

**Issue by Seetch** [ImagicalCorp/PocketMine-0.13.0#194]
[16:13:47] [CRITICAL]: ClassNotFoundException: "Class sky\mysqli not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Seetch** [comment]
https://gist.githubusercontent.com/Humerus/16437ac3267a3340340c/raw/34209087d06af2a260bdf0229b7d2aac64bbae94/Bans.php

it, but created in the folder!

**Comment by thebigsmileXD** [comment]
Has nothing to do with PocketMine or ImagicalMine.
(And its /mysqli or \mysqli btw)

**Comment by Seetch** [comment]
and standart PocketMine !

**Comment by thebigsmileXD** [comment]
-.- instead of for example $db=new mysqli you have to use $db=new \mysqli
And thats NOT a pocketmine bug.

**Comment by Skull3x** [comment]
I don't need your shitty ass plugins anymore.

**Comment by Skull3x** [comment]
I DONT NEED YOR FUCKING PLUGINS BITCH!!!!

**Comment by deotern** [comment]
@Skull3x Kindly pls don't use rude language here....

**Comment by Seetch** [comment]
sorry, and standart SimpleAuth!

**Comment by thebigsmileXD** [comment]
Oh, you say that late @Seetch . Maybe ask the official team, seems to be a bug in the plugin, not ImagicalMine
