### ISSUE TITLE
Corrupt file

### ISSUE THREAD

**Issue by jojoe77777** [ImagicalCorp/PocketMine-0.13.0#20]
Build #40 is 1.3 MB...

**Comment by jojoe77777** [comment]
But build #39 is 3.*...

**Comment by deotern** [comment]
I made the build #39... You need to ask @legoboy0215 for build #40 problem...xD Because it's @legoboy0215 made that build

**Comment by keithkfng** [comment]
Corruption. @legoboy0215 will have to fix that.

**Comment by legoboy0215** [comment]
Fixed. Sorry :P
