### ISSUE TITLE
Food reset

### ISSUE THREAD

**Issue by TomasOlsson** [ImagicalCorp/PocketMine-0.13.0#202]
Food reset when you logout/login.

**Comment by keithkfng** [comment]
Of course it does. It's a problem with your auto plugin LOL

**Comment by robske110** [comment]
? Why would a auth plugin have to do something with that?

**Comment by keithkfng** [comment]
Sorry. My mistake. He said "logout", LOL

**Comment by robske110** [comment]
Reopen?

**Comment by robske110** [comment]
Will test it my self now

**Comment by keithkfng** [comment]
Of course food will reset. The server doesn't save any data on food to players...

**Comment by robske110** [comment]
Confirmed!
![image](https://cloud.githubusercontent.com/assets/16020100/11531455/33947b3a-98fd-11e5-8b77-86ad41c97fdc.png)
After relogin:
![image](https://cloud.githubusercontent.com/assets/16020100/11531456/339a6fea-98fd-11e5-8e03-822eb5762478.png)

**Comment by robske110** [comment]
This should be saved in the player.dat!

**Comment by keithkfng** [comment]
Why? This was never meant to be saved to players. I don't get why this is an issue.

**Comment by robske110** [comment]
Theoretically:
Pocketmine should work exactly as pocketEdition in singleplayer/local multiplayer
The-is-state:
Pocketmine can only do 75% of this.
So this is an issue, maybe not with high priority but it is an issue!

**Comment by keithkfng** [comment]
I don't think it should've saved to players. Anyway, I'll open a poll on Twitter and see what we get. Follow @ImagicalCorp for news.

**Comment by robske110** [comment]
BTW there is a poll function in twitter

**Comment by thebigsmileXD** [comment]
Well, why fixing this bug? thats an awesome feature :joy:

**Comment by robske110** [comment]
Nope, players will use this

**Comment by XiangZhao969** [comment]
How about a config under server.properties? That would be awesome for all :smile:

**Comment by robske110** [comment]
And already "6" likes on Twitter, looks like the community wants it

**Comment by robske110** [comment]
@XiangZhao969 Maybe under pocketmine.yml Server.properties aren't supported anymore

**Comment by XiangZhao969** [comment]
@robske110 Yea, maybe :question:

**Comment by Skull3x** [comment]
Why is this showing in my email xD

**Comment by Skull3x** [comment]
And my account was hacked i guess, soo... :I

**Comment by Skull3x** [comment]
[image: Inline image 1]
Yep, and if you're wondering about the tab at the top left its a project of
mine "google scholar"

**Comment by keithkfng** [comment]
@Skull3x see? I knew it! That's how humans are...

**Comment by deotern** [comment]
@robske110 
Due I'm lazy to look into how to save these things into player.dat, so I won't do it... LOL

But, I'm re-writing it to this for my server, I can merge this into ImagicalMine if you guys wanted:
When you eat food, you gain health, but no hunger ticking, as health is saved into player.dat, so this can fix your not-saved hunger problem...
In another word, I'm reverting to original Pocketmine food eating "system", eat and get health, just pretend hunger isn't exist
Still don't understand? Go to Hypixel and check it out, I'm doing exactly what Hypixel doing

**Comment by robske110** [comment]
@deotern
Why not saving 1 hunger state in player.dat for ALL worlds!

**Comment by deotern** [comment]
@robske110 I said, idk how.... zzz
But, i already finished re-write Pocketmine (Minedox-LITE-Build), which it gives u health when u are eating, as health can be saved into player.dat, so this can solved your problem... But, i will only merge this into public Pocketmine (ImagicalMine) if many people asked for this... Because as I know some people still like the original hunger and food system...
