### ISSUE TITLE
yaml phrase error when server is starting

### ISSUE THREAD

**Issue by deotern** [ImagicalCorp/PocketMine-0.13.0#203]
===
WARNING RuntimeException: "yaml_parse(): parsing error encountered during parsing: did not find expected key (line 21, column 3), context while parsing a block mapping (line 19, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 143
===

Can somebody fix this?? This happened when server is starting

**Comment by keithkfng** [comment]
Plugin problem I think. Or config file - pocketmine.yml

**Comment by deotern** [comment]
Anybody get this error? Or just me? ...

**Comment by keithkfng** [comment]
Just you.

**Comment by thebigsmileXD** [comment]
-.-" oh god. Just delete the pocketmine.yml
