### ISSUE TITLE
Error: Value -3 exceeds the range!

### ISSUE THREAD

**Issue by peepzandmeepz** [ImagicalCorp/PocketMine-0.13.0#208]
PocketMine-MP Crash Dump Wed Dec 2 09:23:51 CST 2015

Error: Value -3 exceeds the range!
File: /src/pocketmine/entity/Attribute
Line: 102
Type: notice

Code:
[93]             return $this;
[94]         }
[95] 
[96]         public function getValue(){
[97]             return $this->currentValue;
[98]         }
[99] 
[100]         public function setValue($value){
[101]             if($value > $this->getMaxValue() or $value < $this->getMinValue()){
[102]                 throw new \InvalidArgumentException("Value $value exceeds the range!");
[103]             }
[104] 
[105]         $this->currentValue = $value;
[106] 
[107]         if($this->shouldSend)
[108]             $this->send();
[109]         }
[110] 
[111]         public function getName(){
[112]             return $this->name;

Backtrace:
#0 /src/pocketmine/entity/Entity(613): pocketmine\Player->setHealth(double -3)
#1 /src/pocketmine/entity/Living(106): pocketmine\entity\Entity->attack(double 19, pocketmine\event\entity\EntityDamageEvent object)
#2 /src/pocketmine/Player(3398): pocketmine\entity\Living->attack(double 19, pocketmine\event\entity\EntityDamageEvent object)
#3 /src/pocketmine/entity/Entity(1009): pocketmine\Player->attack(double 19, pocketmine\event\entity\EntityDamageEvent object)
#4 /src/pocketmine/entity/Entity(992): pocketmine\entity\Entity->fall(double 22.146255493164)
#5 /src/pocketmine/entity/Entity(1257): pocketmine\entity\Entity->updateFallState(double -1.3718109130859, boolean 1)
#6 /src/pocketmine/Player(1392): pocketmine\entity\Entity->move(double 0.017768859863281, double -1.3718109130859, double -0.0082855224609375)
#7 /src/pocketmine/Player(1538): pocketmine\Player->processMovement(integer 1)
#8 /src/pocketmine/Server(2336): pocketmine\Player->onUpdate(integer 1569)
#9 /src/pocketmine/Server(2505): pocketmine\Server->checkTickUpdates(integer 1569, double 1449069831.4467)
#10 /src/pocketmine/Server(2227): pocketmine\Server->tick(boolean)
#11 /src/pocketmine/Server(2105): pocketmine\Server->tickProcessor(boolean)
#12 /src/pocketmine/Server(1706): pocketmine\Server->start(boolean)
#13 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/PocketMine-MP.phar/, string /home/minecraft/multicraft/servers/server8/, string /home/minecraft/multicraft/servers/server8/plugins/)
#14 (1): require_once(string phar:///home/minecraft/multicraft/jar/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by InfornoFire** [comment]
happens to me too

**Comment by InfornoFire** [comment]
actually,  -7 and -13

**Comment by deotern** [comment]
Happens to me too... -1, -8 zzz :P

**Comment by MCPEPIG** [comment]
Fixed.

**Comment by robske110** [comment]
1e289e9 
And
de67022

**Comment by robske110** [comment]
1e289e9
