### ISSUE TITLE
Untested hunger tweaks

### ISSUE THREAD

**Issue by deotern** [ImagicalCorp/PocketMine-0.13.0#209]
https://github.com/ImagicalCorp/PocketMine-0.13.0/commit/9794ea29f80da433a41f8d34d961275b6f352920
I submitted a commit to prevent sprinting get disabled in creative and spectator mode... But due to this code is written by me, and I'm afraid it will be bugged out, so can somebody test this for me?
*Sometimes idk why I will make common mistake in coding even I already knew I will do that...*

**Comment by XiangZhao969** [comment]
Did you check the Travis?
