### ISSUE TITLE
Chests/item pickup

### ISSUE THREAD

**Issue by XFuryMCPE** [ImagicalCorp/PocketMine-0.13.0#21]
If you have a full inventory you can still pickup items, and you can't put items inside chests or take them out, they just stay in your inventory/chest after leaving them

**Comment by keithkfng** [comment]
Something to do with player interaction.

**Comment by Driesboy** [comment]
I have the same problem

**Comment by keithkfng** [comment]
Can you try and fix this please! It's okay if you don't have time.

**Comment by thebigsmileXD** [comment]
Looked into the code. Seems to be a bug within the package handling.

**Comment by keithkfng** [comment]
Can you try and fix it, thanks'

**Comment by thebigsmileXD** [comment]
I have no idea how to change package stuff :package:

**Comment by keithkfng** [comment]
Never mind then

**Comment by thebigsmileXD** [comment]
Just uploaded a new phar and made a test server: 5.175.226.133:19133
It runs, can someone join? I wont, still on 0.11 xD
