### ISSUE TITLE
Hunger depletes too quicky compared to usual

### ISSUE THREAD

**Issue by Pro1000** [ImagicalCorp/PocketMine-0.13.0#210]
Hunger in the server is depleting more quickly than it should be 
Many people are running out of hunger a few minutes after joining the server

**Comment by robske110** [comment]
It's already fixed

**Comment by robske110** [comment]
But not in the newest build

**Comment by thebigsmileXD** [comment]
It is. In 373 or so, as he said, the latest

**Comment by deotern** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/commit/3f7a7a0fc37e9c56dbb4f760745dddb6ce90a5e6
Fixed by me looong ago
