### ISSUE TITLE
PHP 7 coming soon??

### ISSUE THREAD

**Issue by Rodrigo294X** [ImagicalCorp/PocketMine-0.13.0#211]
PHP 7 was finally officially released. Does pocketmine will be upgraded to php7 coming soon??

**Comment by robske110** [comment]
No

**Comment by keithkfng** [comment]
Maybe... If you help us.

**Comment by keithkfng** [comment]
BTW please post questions and chat on our Gitter chatroom. Don't post it here.

**Comment by thebigsmileXD** [comment]
I'll take a look at it
