### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ZenaGamingsky** [ImagicalCorp/PocketMine-0.13.0#25]
There is a bug with doors don't work double plants are broken add some of the block to pocketmine in 0.13.0 rabbits don't work and also there a bug where you select a item in creative and gives you a iron shovel fix them.

**Comment by keithkfng** [comment]
1. The title isn't descriptive. "Bugs" doesn't explain anything.
2. Double plants? Rabbits aren't implemented into PocketMine, duh
3. Iron shovel? The team will look into that, apparently, it should be fixed though. Which build are you using?

**Comment by ZenaGamingsky** [comment]
PocketMine-MP1.7 build 40

**Comment by ZenaGamingsky** [comment]
1. the double plats don't work 
2. Spawn eggs don't be have like they do in mcpe they don't even move.

**Comment by keithkfng** [comment]
1. Try using build #39.
2. What the heck are double plants?
3. Only villager and zombie spawn eggs are implemented into PocketMine at the moment.

**Comment by ZenaGamingsky** [comment]
3. chest are broken in your pocketnine

**Comment by ZenaGamingsky** [comment]
Take a look at rose bush

**Comment by ZenaGamingsky** [comment]
Take a look at rose bush and tall grass there. Double plats and fix the chest in survival

**Comment by keithkfng** [comment]
Yes we know chests, don't duplicate an issue. Read the README thread. We'll look into build #40.

**Comment by ZenaGamingsky** [comment]
Ok

**Comment by thebigsmileXD** [comment]
Also, Double plants weren't implemented.. and mobs also! This "report" is totally wrong.

**Comment by ZenaGamingsky** [comment]
Would you like some help fixing bugs I know some php as well

**Comment by keithkfng** [comment]
Read the README thread before submitting an issue and pull request.

**Comment by ZenaGamingsky** [comment]
Can you fix chest and more stuff

**Comment by thebigsmileXD** [comment]
I don't want to say it, but.. This is not a forum, neither a chat

**Comment by keithkfng** [comment]
We'll try our best.
