### ISSUE TITLE
Some of my plugins doesnt support 

### ISSUE THREAD

**Issue by GamerXzavier** [ImagicalCorp/PocketMine-0.13.0#27]
still hoping that developer of plugin make an update XD

Not Working ->DevTools plugin

**Comment by thebigsmileXD** [comment]
Devtools always works.. Any errors?

**Comment by GamerXzavier** [comment]
devtools disable by itself

**Comment by thebigsmileXD** [comment]
> "Any errors?"

**Comment by GamerXzavier** [comment]
its seem fine and dont have any crash but have just a normal bug

**Comment by thebigsmileXD** [comment]
.. so theres no message WHY DevTools disables itself?

**Comment by GamerXzavier** [comment]
yeah i checked

**Comment by GamerXzavier** [comment]
i tried install and uninstall back still the same ouh and the redstone and there a creative bug of buttons and also cant kill some of the monster

**Comment by thebigsmileXD** [comment]
1. Monsters aren't even implemented
2. Redstone is not implemented
3. so buttons can't work
4. I'll check the devtools out

**Comment by GamerXzavier** [comment]
thanks for helping me out and good luck for making a full working and most no bug free pocketmine for mcpe 0.13

**Comment by thebigsmileXD** [comment]
Thanks. I just tried to use DevTools, it worls atleast with the source folder
