### ISSUE TITLE
Check if server crashes when you kick a player

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/PocketMine-0.13.0#28]
Thanks in advance

**Comment by thebigsmileXD** [comment]
IP: 5.175.226.133
Port: 19133

**Comment by GamerXzavier** [comment]
your server didnt open

**Comment by thebigsmileXD** [comment]
*facepalm* wait, join in 5 minutes

**Comment by thebigsmileXD** [comment]
Well.. my firewall settings are correct.

**Comment by keithkfng** [comment]
I'll try joining.

**Comment by thebigsmileXD** [comment]
Okay.. crash: no
Errors:
Every frickin' tick: [Server thread/CRITICAL]: Could not tick level "world": Undefined variable: x

**Comment by keithkfng** [comment]
Wow...

**Comment by thebigsmileXD** [comment]
Searching for it.. Did skins work? Or have you seen anything?

**Comment by keithkfng** [comment]
Nope, I haven't tested it yet... Apparently, it's working.

**Comment by deotern** [comment]
@thebigsmileXD Don't install FastTransfer or transfer player, based on my experiences on PM 1.6, it's a bug related with transferred packets thingy...

**Comment by keithkfng** [comment]
@zombie_Power from PocketMine forums is attempting to fix the problem, he just messaged me via Twitter. Although he's new to GitHub, he probably will fix it, I don't know.

**Comment by thebigsmileXD** [comment]
@deotern I only have DevTools installed :fearful:

**Comment by keithkfng** [comment]
Uninstall that as well and try

**Comment by deotern** [comment]
Hmm, strange tho... @keithkfng what's your Twitter btw, I'll follow you ;)

**Comment by thebigsmileXD** [comment]
Uh.. Can someone join again?
i think its the position...

**Comment by keithkfng** [comment]
@keithkfng XD Lel same, but my forum usernames are @k3ithkfng, I don't know why and I haven't been bothered to fix it again

**Comment by keithkfng** [comment]
I'll try again then

**Comment by thebigsmileXD** [comment]
Its there xD

**Comment by keithkfng** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/issues/29
Not really working... The loading bar never loads, someone reported it.

**Comment by thebigsmileXD** [comment]
The error shows up until you leave

**Comment by keithkfng** [comment]
Hmmm, what's the problem? Something to do with world loading.

**Comment by thebigsmileXD** [comment]
Uhm, what loading bar? the one when you try to join?

**Comment by keithkfng** [comment]
Yes, the one that goes "Building terrain..."

**Comment by thebigsmileXD** [comment]
xD LevelLoadEvent:
The one comment:
> "Loaded when the level saves" xD

**Comment by keithkfng** [comment]
Any fix for it?

**Comment by thebigsmileXD** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/blob/master/src/pocketmine/level/Level__64bit.php or https://github.com/ImagicalCorp/PocketMine-0.13.0/blob/master/src/pocketmine/level/Level__32bit.php is corrupted.. i think i saw that somewhere once

**Comment by keithkfng** [comment]
Maybe copy from main repo @ PocketMine/PocketMine-MP again?

**Comment by deotern** [comment]
Create a branch, copy from #48 Bleeding... :)

**Comment by keithkfng** [comment]
Will do...

**Comment by thebigsmileXD** [comment]
it was a bug in 1.5..

**Comment by keithkfng** [comment]
But they got it working. How?

**Comment by astersx** [comment]
i have 2 runing server and 1 i test your builds,  and wait for a little fix to use it on my main server :)

**Comment by thebigsmileXD** [comment]
I am searching for the build where it got fixed.. currently haven't found it

**Comment by keithkfng** [comment]
What about #48 Bleeding as @deotern said?

**Comment by keithkfng** [comment]
Accidentally closed it oops lel

**Comment by astersx** [comment]
Hey bro,  can you fix shove transformation? :)

**Comment by keithkfng** [comment]
Will do. Open an issue please.

**Comment by astersx** [comment]
Done,  and goooood luck :)

**Comment by thebigsmileXD** [comment]
Could we use Travis for compiling please? Don't want to download it every time and compile it..

**Comment by keithkfng** [comment]
WTF is Travis?

**Comment by thebigsmileXD** [comment]
An automated building tool. Pocketmine uses it. https://travis-ci.org/getting_started
I use it on my profile (enabled it) but have nothing to compile yet ;)

**Comment by keithkfng** [comment]
That'd be nice, why about Jenkins?

**Comment by thebigsmileXD** [comment]
hmm.. Is that also so easy to implement? Travis checks if the build is corrupt. Jenkins creates the build

**Comment by keithkfng** [comment]
I'm not sure. Setup Travis for now, it might actually be useful.

**Comment by keithkfng** [comment]
I'm not sure. Setup Travis for now, it might actually be useful.

**Comment by thebigsmileXD** [comment]
Join again.. had an idea

**Comment by keithkfng** [comment]
Can't, using my phone with no MCPE on it sorry.

**Comment by thebigsmileXD** [comment]
And also.. The owner of the  repo has to accept travis to be added.. i already requested it

**Comment by keithkfng** [comment]
Fine... Where do I accept it

**Comment by thebigsmileXD** [comment]
No idea, under settings?

**Comment by keithkfng** [comment]
Will check that...

**Comment by thebigsmileXD** [comment]
Applications

**Comment by keithkfng** [comment]
Not there... No applications. What if I just made you another owner of the repo, would that work?

**Comment by thebigsmileXD** [comment]
Guess so, you can remove me afterwards i think

**Comment by keithkfng** [comment]
Done, try installing again.

**Comment by thebigsmileXD** [comment]
Was easy. Imagical Corporation (still, its a typo: Coorporation)->settings->third party access->travis, requested by thebigsmileXD->details->grant access

**Comment by keithkfng** [comment]
Imagical Corporation. I don't see a typo anywhere.

**Comment by thebigsmileXD** [comment]
https://en.wikipedia.org/wiki/Corporation_(disambiguation)
Aren't we moreeeee... Oh wait.. \*facepalm\* my fault.. and wikipedia's xD

**Comment by keithkfng** [comment]
Lel

**Comment by thebigsmileXD** [comment]
Uhm.. what build is it now? i want to compile the one with the grass fix /joinbug fix

**Comment by keithkfng** [comment]
I was hoping to fix the other bugs in the issues section before compiling again.

**Comment by thebigsmileXD** [comment]
Just had a ddos or so. Whole server wasn't reachable and ping 100% loss.

**Comment by thebigsmileXD** [comment]
Or someone accidently unplugged the cable and fell on his nose because his foot hang on the cable :P

**Comment by thebigsmileXD** [comment]
Can someone try to join again?

**Comment by 3rdIteration** [comment]
Joining now. Building Terrain took a while but I am guessing that was the initial chunk generation. Inventory item is still toggling away but I can move around, change things, etc.

**Comment by thebigsmileXD** [comment]
:open_mouth: 100% load on 1 player. But the build works

**Comment by keithkfng** [comment]
Upload it, and create a new release!

**Comment by thebigsmileXD** [comment]
Okay, thanks to @3rdIteration !
Skins are still black to each other, but its stable. What build is this?

**Comment by thebigsmileXD** [comment]
btw, travis is enabled

**Comment by keithkfng** [comment]
Check the commits
