### ISSUE TITLE
Error when joining Build #59

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/PocketMine-0.13.0#29]
I get the following error in the console window when joining the latest build #59. In the game the wold never fully loads.

2015-11-20 [10:20:26] [Server thread/CRITICAL]: Could not tick level "world": Undefined variable: x

**Comment by keithkfng** [comment]
We're currently testing this issue with @thebigsmileXD, it will soon be fixed. Thanks for the report!

**Comment by NML32** [comment]
Thanks for all your hard work on this project!! You guys are polite and quick to respond two thumbs up.

Fyi, I'm unable to join the server so I can't test the kick command.

**Comment by keithkfng** [comment]
That's alright, and thanks for your support! We have tested the kick command - but came across the error you have. We will be working to fix this soon!

**Comment by keithkfng** [comment]
The world problem should be fixed now. Wait for the latest build.

**Comment by thebigsmileXD** [comment]
Seems to happen on flat worlds only, and only in the 0,0 chunk
