### ISSUE TITLE
Issa keeps switching arrow and block

### ISSUE THREAD

**Issue by carstenberger** [ImagicalCorp/PocketMine-0.13.0#30]
Keeps switching between arrow and block! Is this a known issue?

**Comment by keithkfng** [comment]
Inventory hotbar glitch... again. That isn't a known issue at the moment. Which build are you using?

**Comment by carstenberger** [comment]
I’m quite new to pocketmine server. 

Used latest build phar release PocketMine-MP_1.7dev#--.phar

 

thanks

 

Van: Keith The Koder [mailto:notifications@github.com] 
Verzonden: vrijdag 20 november 2015 11:29
Aan: ImagicalCorp/PocketMine-0.13.0
CC: SOLIT | Carsten
Onderwerp: Re: [PocketMine-0.13.0] Issa keeps switching arrow and block (#30)

 

Inventory hotbar glitch... again. That isn't a known issue at the moment. Which build are you using?

—
Reply to this email directly or view it on GitHub <https://github.com/ImagicalCorp/PocketMine-0.13.0/issues/30#issuecomment-158350779> . <https://github.com/notifications/beacon/AHUlAVGVdmO_96TiR0AsQt3_vZ-iHR97ks5pHu2BgaJpZM4GmRFl.gif> 


 
Carsten Berger
M: 
E: carsten@solit.nl
 
SOLIT
Zuiddijk 255 A
1501 CK Zaandam
T: +31 (0)75 6315601
F: +31 (0)75 7501119
W: http://www.solit.nl/
 
 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dit bericht kan informatie bevatten die niet voor u is bestemd. Indien u niet de geadresseerde bent of dit bericht abusievelijk aan u is toegezonden, wordt u verzocht dat aan de afzender te melden en het bericht te verwijderen. SOLIT aanvaardt geen aansprakelijkheid voor schade, van welke aard ook, die verband houdt met risico's verbonden aan het elektronisch verzenden van berichten.
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. SOLIT accepts no liability for damage of any kind resulting from the risks inherent in the electronic transmission of messages.

**Comment by keithkfng** [comment]
Which phar did you download?

**Comment by carstenberger** [comment]
Don’t know if im doing it correct but i user your /release/PocketMine-MP_1.7dev#--.phar

**Comment by keithkfng** [comment]
Try #39.

**Comment by carstenberger** [comment]
Same thing in build #39, do i doing something wrong?

**Comment by keithkfng** [comment]
Okay, will fix.

**Comment by carstenberger** [comment]
Thanks! I let you know if it was fixed on my server

**Comment by Driesboy** [comment]
Hoi ik zie dat je nederlands bent

**Comment by carstenberger** [comment]
Ja klopt!

Heb jij verstand van dat mp server gedoe? Mn dochter is erg verdrietig omdat ze niet meer kam inloggen

Verstuurd vanaf mijn iPhone

> Op 20 nov. 2015 om 17:28 heeft Driesboy <notifications@github.com> het volgende geschreven:
> 
> Hoi ik zie dat je nederlands bent
> 
> —
> Reply to this email directly or view it on GitHub.
> 

 
Carsten Berger
M: 
E: carsten@solit.nl
 
SOLIT
Zuiddijk 255 A
1501 CK Zaandam
T: +31 (0)75 6315601
F: +31 (0)75 7501119
W: http://www.solit.nl/
 
 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dit bericht kan informatie bevatten die niet voor u is bestemd. Indien u niet de geadresseerde bent of dit bericht abusievelijk aan u is toegezonden, wordt u verzocht dat aan de afzender te melden en het bericht te verwijderen. SOLIT aanvaardt geen aansprakelijkheid voor schade, van welke aard ook, die verband houdt met risico's verbonden aan het elektronisch verzenden van berichten.
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. SOLIT accepts no liability for damage of any kind resulting from the risks inherent in the electronic transmission of messages.

**Comment by carstenberger** [comment]
Still issue with #79 build

**Comment by carstenberger** [comment]
sorry i ment the #72 build

**Comment by legoboy0215** [comment]
Yep. I confirm it :)

**Comment by keithkfng** [comment]
Just checked this, if you tap another block in the inventory it will stop the glitch for your session. I don't think this can be fixed, but at least it works for now.

**Comment by legoboy0215** [comment]
No, it does not. I can switch everything to all slots and it still changes :P

**Comment by keithkfng** [comment]
Really? It worked for me on @thebigsmileXD's test server.

**Comment by keithkfng** [comment]
http://docs.pocketmine.net/db/dbc/classpocketmine_1_1event_1_1inventory_1_1_inventory_event.html

**Comment by thebigsmileXD** [comment]
I did something in my OITC. When the game starts, i assign all hotbarslots new. Inv.-slot 1 = hotbarslot 1 etc.
This works nicely. But if you want to use a different slot.. Or rejoin.. Its the issue again
