### ISSUE TITLE
Items glich and armour

### ISSUE THREAD

**Issue by astersx** [ImagicalCorp/PocketMine-0.13.0#31]
Hi,  i wanna to let you know about some gliches :) 
- Wen you click a item it transform to iron shovel.
-Armours cant equip.
P.S. skins still black (i dont care so much about skins)

**Comment by keithkfng** [comment]
Which build are you using? Build #59 fixes skins.

**Comment by astersx** [comment]
59 still not fixed skins

and my console is spammed and building terrain not load sometimes
console is spammed with
[06:06:42] [Server thread/CRITICAL]: Could not tick level "world": Undefined variable: x

**Comment by keithkfng** [comment]
Yes, there is an error with that build, sorry.

**Comment by astersx** [comment]
Omg i stopped server :0...  But spam like,  10 warnings/second

**Comment by Driesboy** [comment]
Use the new build

**Comment by astersx** [comment]
Already use it....  but i really wanna inventory to be fixed :(

**Comment by thebigsmileXD** [comment]
I guess i have to check it out? Lol

**Comment by legoboy0215** [comment]
LOL You are the only dev :P

**Comment by keithkfng** [comment]
If you tap another item in the inventory, it will stop the glitch for your session time which you are online for. This won't be fixed. No point spending so much time on something that has a quick fix.

**Comment by EnderKenji** [comment]
When the inventory bug will be fix? Because this is he most important thing on server. ._.

**Comment by keithkfng** [comment]
This will be fixed in an upcoming release. The team is working hard to fix this. If you feel like you can help, fork this repo, make some changes and submit a pull request!

**Comment by thebigsmileXD** [comment]
This was a bug in 0.11 creative also.
