### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RafeeSamith** [ImagicalCorp/PocketMine-0.13.0#32]
Does this use PHP7?
If so please add one with mcpe 0.13.0
(Because in jenkins bleeding pocketmine files the ones with origin/php7 doesnt work

**Comment by thebigsmileXD** [comment]
It does, and php7 is implemented

**Comment by RafeeSamith** [comment]
Thx! This is the first time someone has replied instantly XD

**Comment by keithkfng** [comment]
Glad to know this issue has been resolved.

**Comment by RafeeSamith** [comment]
💙

**Comment by RafeeSamith** [comment]
MinePocket is already using this?
Keep up the good work!

**Comment by RafeeSamith** [comment]
(MinePocket is a server)

**Comment by keithkfng** [comment]
Is it? Gee, I'm proud of all of the community for making this happen! Keep it up!
