### ISSUE TITLE
Item invotory glitch and chest

### ISSUE THREAD

**Issue by ZenaGamingsky** [ImagicalCorp/PocketMine-0.13.0#34]

**Comment by ZenaGamingsky** [comment]
Hi there is still a bug with creative ivotey bar seleting a item it does this you click the block you want gliches to iron sovel and so on.

**Comment by ardaozkal** [comment]
Can you try to write this more clearly?

**Comment by astersx** [comment]
wen you click a item,  it transform to iron shovel,  or just vanish for some time...

**Comment by ardaozkal** [comment]
Checking.

**Comment by Driesboy** [comment]
I have the same problem

**Comment by RafeeSamith** [comment]
are you using #39 or #59?

**Comment by ZenaGamingsky** [comment]
70

**Comment by ZenaGamingsky** [comment]
There is also a chest bug on survival.
