### ISSUE TITLE
pocketmine

### ISSUE THREAD

**Issue by astersx** [ImagicalCorp/PocketMine-0.13.0#4]
Hi,  were i can get phar?  Becouse if i try to arhive any pocketmine plugin,  it dont work,  but other plugins work,  so what program i need to use for pocketmine? P.S. Forum closed or just down,  i cant enter so i post here

**Comment by keithkfng** [comment]
Install DevTools, place the zip file inside the DevTools folder, then run /makeserver on console to compile it.
