### ISSUE TITLE
Invalid Name error when there is a space in the username

### ISSUE THREAD

**Issue by ardaozkal** [ImagicalCorp/PocketMine-0.13.0#43]
As I play the Minecraft Windows 10 Edition, I can't change my name. (http://ardao.me/files/rup.png)

And I picked a Xbox username with a space in it 2 years ago (yep I'm an idiot).

As I don't have an Xbox I can't change my username (I'm even willing to pay lol).

**Comment by PEMapModder** [comment]
Use the NameCorrector plugin.

**Comment by ardaozkal** [comment]
Making it official would be better, but whatever.
