### ISSUE TITLE
I would love to help out

### ISSUE THREAD

**Issue by DRedDogPE** [ImagicalCorp/PocketMine-0.13.0#46]
I would love to help out if you are trying to update to 0.13.0, atm i am working on redstone features and i have already added the new doors, every block and item id and alot of the features from 0.12.3

**Comment by DRedDogPE** [comment]
https://github.com/EliteCrafterz/PocketMine-MP/commit/9317890573e89b7dfd44d0c69da3301454818a10

**Comment by keithkfng** [comment]
Sure, we'll add you on the dev team.
