### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by peepzandmeepz** [ImagicalCorp/PocketMine-0.13.0#48]
Getting this error on startup on latest source...

Fatal error: Class pocketmine\entity\Chicken contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (pocketmine\entity\Living::getName) 

Unsure as to whether I can report this (as the build was just posted), but just wanted to let you know.

What this organization is doing is fantastic! Thanks for this :)

**Comment by deotern** [comment]
Yes, thank you for reporting this :)
But dont use latest source code build, its unstable :)
You can either download from http://pocketmine.minedox.com or directly from resources folder :)

**Comment by EpicSteve33** [comment]
[143] class Player extends Human implements CommandSender, InventoryHolder, ChunkLoader, IPlayer{ 


this is what crashes the server i checked the crash dumb and this is the cause

**Comment by DRedDogPE** [comment]
I think this is fixed
