### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rodrigo294X** [ImagicalCorp/PocketMine-0.13.0#52]
[NOTICE]: RuntimeException: "Declaration of pocketmine\Player::setSkin() should be compatible with pocketmine\entity\Human::setSkin($str, $skinflag, $isSlim = false)" (E_STRICT) in "/src/pocketmine/Player__32bit" at line 143

**Comment by keithkfng** [comment]
Should be fixed in the latest upcoming build.
