### ISSUE TITLE
Unable to get items from chest.

### ISSUE THREAD

**Issue by legoboy0215** [ImagicalCorp/PocketMine-0.13.0#55]
^^^ Title says it all. Once you get it, when you exit the chest screen the item disappears. IDK if this issue exists or not, so I opened this :)

**Comment by deotern** [comment]
Eh.... don't tag it wontfix xD There's chest in my minigame, Smash! :(

**Comment by keithkfng** [comment]
Well, can someone fix this?

**Comment by deotern** [comment]
Im looking into it right now but I don't sure if I can fix it :)

**Comment by keithkfng** [comment]
Great! Thanks.

**Comment by deotern** [comment]
First, we need someone to proof if this bug exist...

**Comment by keithkfng** [comment]
Imagical Corporation test server by @thebigsmileXD

**Comment by keithkfng** [comment]
![image](https://cloud.githubusercontent.com/assets/13236085/11317489/99ed7610-9084-11e5-841d-bb34e473f8be.png)

**Comment by deotern** [comment]
Let me create a easier IP for u... its so looong... @@
How about?
imagical.minedox.com:19133?

**Comment by keithkfng** [comment]
Yep, I'll join, and test it. The inventory bug had a temp fix for it, but it's annoying and must be done on client side. Basically, you just keep tapping the item again and again until the shovel disappears.

**Comment by deotern** [comment]
I have set it up, try it:
IP: imagical.minedox.com
Port: 19133

**Comment by deotern** [comment]
Tested, able to connect :) But I'm in 0.12.3 now, because I run few test on my server, can anyone join imagical.minedox.com and test the chest bug? :D

**Comment by GamerXzavier** [comment]
sure

**Comment by GamerXzavier** [comment]
the server is on 0.11 i cant join XD

**Comment by keithkfng** [comment]
It's not online...

**Comment by deotern** [comment]
![screenshot_2015-11-21-16-34-57](https://cloud.githubusercontent.com/assets/14260477/11317572/d7b89126-906d-11e5-8b60-62c15c5a62a4.png)
Its online! zzz
Make sure port is 19133

**Comment by GamerXzavier** [comment]
its online! i played just now
the chest is fine and the shovel bug seem gone now i think XD

**Comment by GamerXzavier** [comment]
see the port its 19133

**Comment by keithkfng** [comment]
Still can't connect. Something wrong with my client I think.

**Comment by deotern** [comment]
@GamerXzavier So, u tested it?

**Comment by keithkfng** [comment]
Yep, he did.

**Comment by legoboy0215** [comment]
WHAT??? Check my server: play.legocraft.me:19132
HG chests don't work -_-

**Comment by keithkfng** [comment]
@deotern post your phar here and let @legoboy0215 test it

**Comment by deotern** [comment]
Wait.... my phar? That imagical.minedox.com:19133 is your server.... And @GamerXzavier tested on it,... In another way, he test it on YOUR server... How can i get your server phar?? @-@ LOL

**Comment by keithkfng** [comment]
So you used build #72 and it it worked?

**Comment by deotern** [comment]
Its your server, how can i know....

**Comment by keithkfng** [comment]
??? I'm talking about imagical.minedox.com:19133.

**Comment by deotern** [comment]
Yeah, and imagical.minedox.com:19133 is your server... not mine... How can i know what is the build number of Pocketmine on that server... ???

**Comment by keithkfng** [comment]
Don't you host it?

**Comment by legoboy0215** [comment]
Server is yours, domain is his.

**Comment by carstenberger** [comment]
Can someone please tell me the steps to install a server from scratch? i used developer server from pocketmine.net maybe this is an issue? i use osxserver to run pe server.

**Comment by deotern** [comment]
To install, first download it from:
http://pocketmine.minedox.com
I will add a description guide at that website later since many people dont know how to install :)

*And please create a new issue for this, don't talk about the things that are not related with the topic here

**Comment by legoboy0215** [comment]
Everyone should be able to report this bug and comment on it.

**Comment by keithkfng** [comment]
It's going off-topic now...

**Comment by carstenberger** [comment]
Some people do have the issue some people don't, so maybe they not doing the install of the server the right way and update the phar. So my question is, what to do from scratch to let the #72 build run correctly without the 'items' issue. We want to now what the developers did, cause they havent got those issues.

**Comment by thebigsmileXD** [comment]
Uhm.. Thats even longer and thats not an ip, its dns

**Comment by keithkfng** [comment]
@thebigsmileXD What build version did you use?

**Comment by keithkfng** [comment]
@carstenberger The item bug hasn't been "fixed", sometimes it doesn't come up and sometimes it does. We don't know what the developers did to get it working in some cases.

**Comment by carstenberger** [comment]
when i login imagical.minedox.com the bug is also there.
strange issue

**Comment by thebigsmileXD** [comment]
I am at my gf now. The whole weekend. Do you think i habe time?!

**Comment by legoboy0215** [comment]
Oh sorry :P

**Comment by keithkfng** [comment]
http://docs.pocketmine.net/dc/dd1/classpocketmine_1_1event_1_1inventory_1_1_inventory_transaction_event.html

**Comment by ZombiePower** [comment]
I fixed it

**Comment by keithkfng** [comment]
Fixed.

**Comment by legoboy0215** [comment]
Fixed where?

**Comment by keithkfng** [comment]
Skin-patch merge. But now that's introduced a whole lot of other bugs...

**Comment by legoboy0215** [comment]
What bugs?

**Comment by thebigsmileXD** [comment]
Sure its fixed? I would like to try the latest snapshot. Cool things on my server btw. And.. Seems like default generator is normal and not flat?

**Comment by keithkfng** [comment]
It has been fixed.

**Comment by legoboy0215** [comment]
Then why did I see a crash on getTile :P

**Comment by keithkfng** [comment]
Hm...

**Comment by ZombiePower** [comment]
I will trying adding in something that extends getTile()

**Comment by thebigsmileXD** [comment]
You wont need getTile. If the chest is an instance of Chest it will be an instance of \tile\Chest also

**Comment by ZombiePower** [comment]
can you edit it then. I am trying to look into more deeper issues
