### ISSUE TITLE
Compile 

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/PocketMine-0.13.0#6]
@thebigsmileXD can you run DevTools to quickly compile this and put that into a releases folder, can't be bothered soz

**Comment by keithkfng** [comment]
Never mind, I've done it. Takes time to publish.

**Comment by keithkfng** [comment]
Need to re-compile to latest updates.

**Comment by legoboy0215** [comment]
Complier uploaded. All credits to @PEMapModder :) Compile yourself, lazy bone :P Just joking.
