### ISSUE TITLE
Founded new issues

### ISSUE THREAD

**Issue by GamerXzavier** [ImagicalCorp/PocketMine-0.13.0#67]
just now i play on imagical test server...
and its night and i tap bed its say something like "you can only sleep at night"(p.s it night!)

fix it bro.
-#if anyone found a new bug please comment.

**Comment by GamerXzavier** [comment]
Founded new one..
The sound is having slow respond (i just only check the door sound...)

**Comment by Driesboy** [comment]
Op bug

**Comment by GamerXzavier** [comment]
Founded another!
when using bow in creative(survival not tested yet)
you shot and the arrow will go on ground not straight like you want to shot a plank in front of you but the arrow will go to grass.

Ouh and the monster sound also slow respond...

fix.and i test XD

**Comment by keithkfng** [comment]
The sounds won't be fixed. As for the arrows, they work fine for me. I don't know what you're aiming at.

**Comment by Driesboy** [comment]
Ok tnx

**Comment by keithkfng** [comment]
Time issues with beds. Mentioned in another issue.
