### ISSUE TITLE
CavenSpider???

### ISSUE THREAD

**Issue by jojoe77777** [ImagicalCorp/PocketMine-0.13.0#7]
You have a mob called "CavenSpider"... I assume you mean Cave Spider? Typo or not?

**Comment by keithkfng** [comment]
Where is it? Is it in the PocketMine folder? I haven't looked at it closely hahaha

**Comment by keithkfng** [comment]
EDIT: no it isn't a typo, I just had a look at the code - the entity is referred to as CavernSpider throughout the whole file.

**Comment by jojoe77777** [comment]
Oops, I meant CavernSpider. But it's supposed to be CaveSpider.

**Comment by keithkfng** [comment]
I'll look into it, or at least I'll tell @legoboy0215 to look into it with me hehe

**Comment by legoboy0215** [comment]
...

**Comment by thebigsmileXD** [comment]
It is. Thats a joke by the team ;D
