### ISSUE TITLE
#136 could be corrupted!

### ISSUE THREAD

**Issue by deotern** [ImagicalCorp/PocketMine-0.13.0#70]
@keithkfng Submitted a release, #136 with 1MB+ size of phar, it is suspected as corrupted

**Comment by keithkfng** [comment]
Can you recompile it? Thanks!

**Comment by deotern** [comment]
Yes, but give me some time, cuz im out now :P

**Comment by keithkfng** [comment]
Do you use another phar compiler? How come your builds are never corrupted...

**Comment by da123rrell** [comment]
actually you just uploaded 
15:20:16 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)

**Comment by keithkfng** [comment]
I thought so... I can never trust DevTools anymore XD

**Comment by da123rrell** [comment]
:p

**Comment by SirGamer** [comment]
Hey @keithkfng!

When will this build be usable?

We currently use this third-party version of PocketMine for LEET Realms. (A MCPE Server hosting company.) http://leet.cc

And we have had many bugg reports, let us know. Thanks. :)

**Comment by keithkfng** [comment]
We don't know yet. We're having some trouble with the AttributManager problem. We'll keep you updated and let you know ASAP.

**Comment by SirGamer** [comment]
Understood. :)

**Comment by deotern** [comment]
Re-compiled, #143
Download available from:
pocketmine.minedox.com
or you can download directly from repo
