### ISSUE TITLE
missing AttributeManager

### ISSUE THREAD

**Issue by da123rrell** [ImagicalCorp/PocketMine-0.13.0#71]
from the build that I compile from GitHub this happens

[14:44:00] [CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Class pocketmine\entity\AttributeManager not found
[14:44:07] [INFO]: [XXXX] Ban people that broke the rules by doing /v
[14:44:22] [INFO]: [XXXX] All languages are allowed but just dont get mad if ignored.
[14:44:37] [INFO]: [XXXX] Read the rules so you won't get kicked or banned
[14:44:37] [INFO]: Removed 0 entities.
[14:44:37] [INFO]: [/92.214.196.128:19158] logged out due to generic reason

there are no other errors other then that

**Comment by Driesboy** [comment]
I dont have this problem

**Comment by Subtleoliver** [comment]
What build are you running?

**Comment by keithkfng** [comment]
@ZombiePower should be fixing this soon.

**Comment by da123rrell** [comment]
use https://github.com/ImagicalCorp/PocketMine-0.13.0/tree/master/src then I compile it.

**Comment by ZombiePower** [comment]
what do you mean?

**Comment by ZombiePower** [comment]
there is no AttributeManager?

**Comment by keithkfng** [comment]
Look at the issue, attribute manager issue

**Comment by keithkfng** [comment]
Maybe copy file from main repo? Quick fix :P

**Comment by ZombiePower** [comment]
nope... its a new source

**Comment by da123rrell** [comment]
happens again after recompile
[14:59:53] [CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Class pocketmine\entity\AttributeManager not found

**Comment by da123rrell** [comment]
http://s000.tinyupload.com/index.php?file_id=06586390355889122499
the .phar

**Comment by da123rrell** [comment]
and that's a compiled version of 136

**Comment by ZombiePower** [comment]
hm... I don't even see, why it is using pocketmine\entity\AttributeManager....

**Comment by da123rrell** [comment]
maybe someone did a typo or something

**Comment by ZombiePower** [comment]
that's what I am trying to find lol

**Comment by da123rrell** [comment]
well this is strange. it works on my private server but doesn't on my public server

**Comment by da123rrell** [comment]
ooh it happens after someone tried to join

**Comment by ZombiePower** [comment]
hm.... this is quite odd.

**Comment by ZombiePower** [comment]
can you try the latest build?

**Comment by da123rrell** [comment]
I am using the latest build

**Comment by da123rrell** [comment]
hold on, let me try to recompile it

**Comment by da123rrell** [comment]
still happens

**Comment by ZombiePower** [comment]
I am really unsure why this issue is occurring.

**Comment by da123rrell** [comment]
maybe something that someone change that causes this?

**Comment by ZombiePower** [comment]
nope. You are the only one seeming to have this issue.

**Comment by keithkfng** [comment]
Maybe remove the reference towards it in raklib interface?

**Comment by keithkfng** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/tree/attribute-patch try compiling this I don't think it'll work though

**Comment by da123rrell** [comment]
still

**Comment by keithkfng** [comment]
Still same error? You need to recompile btw

**Comment by da123rrell** [comment]
yea I did

**Comment by keithkfng** [comment]
Hm... Something wrong with that.

**Comment by keithkfng** [comment]
@da123rrell have all the skins, inventory and chest bugs been fixed btw?

**Comment by da123rrell** [comment]
i cant even join, how am i supposed to know -_-

**Comment by da123rrell** [comment]
the compiled file
http://s000.tinyupload.com/index.php?file_id=06804423945959967402

**Comment by keithkfng** [comment]
Let's see if @DRedDogPE can work this out...

**Comment by da123rrell** [comment]
lets just hope

**Comment by kam187** [comment]
src/pocketmine/Player__32bit.php:use pocketmine\entity\AttributeManager;
src/pocketmine/Player__32bit.php:        $this->attribute = new AttributeManager($this);
src/pocketmine/Player__32bit.php:            $this->getAttribute()->getAttribute(AttributeManager::MAX_HEALTH)->setValue($amount);
src/pocketmine/Player__32bit.php:        $this->getAttribute()->getAttribute(AttributeManager::MAX_HUNGER)->setValue($amount);
src/pocketmine/Player__64bit.php:use pocketmine\entity\AttributeManager;
src/pocketmine/Player__64bit.php:        $this->attribute = new AttributeManager($this);
src/pocketmine/Player__64bit.php:            $this->getAttribute()->getAttribute(AttributeManager::MAX_HEALTH)->setValue($amount);
src/pocketmine/Player__64bit.php:        $this->getAttribute()->getAttribute(AttributeManager::MAX_HUNGER)->setValue($amount);

**Comment by kam187** [comment]
AttributeManager is for the Katana fork, not normal PocketMine.

**Comment by da123rrell** [comment]
maybe someone accidentally used that for this

**Comment by keithkfng** [comment]
Got it. Will fix it straight away!

**Comment by kam187** [comment]
:)

**Comment by keithkfng** [comment]
What if I just add the file? Would it fix the problem? I doubt it, just looking for comments.

**Comment by kam187** [comment]
Shall i fix it?  give me a few mins.

**Comment by keithkfng** [comment]
Yep, great if you could fork this and make a PR! Thanks!

**Comment by kam187** [comment]
Hmm that's weird, why did someone add this in :P  Ok i'll fix it now.

**Comment by keithkfng** [comment]
I'm wondering to! Someone seems to have just copied Katana code in. Definitely not me, I haven't touched the Katana repo for weeks now.

**Comment by da123rrell** [comment]
I never touched it!

**Comment by kam187** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/commit/aa4e7355862ab504290fcd06273d4a8c02e10630

It was changed by DRedDogPE 15 hours ago.

**Comment by keithkfng** [comment]
Thanks for the reference. Now fixing it myself. Thanks for all your help!

**Comment by keithkfng** [comment]
Fixed. @da123rrell please recompile.

**Comment by kam187** [comment]
Hmm there's other references to getAttribute

pocketmine/Player__32bit.php:    public function getAttribute() {
pocketmine/Player__32bit.php:        $this->getAttribute()->sendAll();
pocketmine/Player__32bit.php:                        $this->getAttribute()->resetAll();
pocketmine/Player__32bit.php:            $this->getAttribute()->getAttribute(AttributeManager::MAX_HEALTH)->setValue($amount);
pocketmine/Player__32bit.php:        $this->getAttribute()->getAttribute(AttributeManager::MAX_HUNGER)->setValue($amount);
pocketmine/Player__64bit.php:    public function getAttribute() {
pocketmine/Player__64bit.php:        $this->getAttribute()->sendAll();
pocketmine/Player__64bit.php:                        $this->getAttribute()->resetAll();
pocketmine/Player__64bit.php:            $this->getAttribute()->getAttribute(AttributeManager::MAX_HEALTH)->setValue($amount);
pocketmine/Player__64bit.php:        $this->getAttribute()->getAttribute(AttributeManager::MAX_HUNGER)->setValue($amount);

Also you didn't remove:
$this->attribute->init();

Did you test it?

Anyway even if i add attribute manager i get:

Call to private pocketmine\entity\Attribute::__construct() from context 'pocketmine\entity\AttributeManager' in Desktop/ImageCraft PocketMine-0.13.0/src/pocketmine/entity/AttributeManager.php on line 76

Not sure why Attributes.php was modified to make the construct private :/

Change that and then an error in:

all to undefined method pocketmine\Player::isSkinTransparent() in Desktop/ImageCraft PocketMine-0.13.0/src/pocketmine/Server__64bit.php on line 2250

The whole skin fix seems broken.

**Comment by da123rrell** [comment]
sflr I was eating

**Comment by keithkfng** [comment]
@kam187 I may as well add you to the organisation so you can make changes, I've got to go, I can't spend 24 hours a day approving pull requests lol

**Comment by mwvent** [comment]
I removed the __64bit and __32bits files to run. This repo is full of them but we are often only updating fixing the base php file which is not getting used because the __32 and __64 bit ones get run instead. These 32,64 bit files aren't in the official repo https://github.com/PocketMine/PocketMine-MP/tree/master/src/pocketmine at all perhaps we can do the same?

**Comment by mwvent** [comment]
https://github.com/ImagicalCorp/PocketMine-0.13.0/commit/a75215447568102eb3422acc96b2fb1605f0a062
Fixed the issue see the comments

**Comment by da123rrell** [comment]
Fatal error: Call to a member function init() on null in C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\Player__32bit.php on line 539

Call Stack:
    0.0623     125768   1. {main}() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\PocketMine.php:0
    0.7573     272088   2. pocketmine\Server->__construct() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\PocketMine.php:464
    4.6696   19075216   3. pocketmine\Server->start() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\Server__32bit.php:1700
    4.7712   19179968   4. pocketmine\Server->tickProcessor() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\Server__32bit.php:2099
   60.3265   19185616   5. pocketmine\Server->tick() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\Server__32bit.php:2221
   60.3266   19185680   6. pocketmine\network\Network->processInterfaces() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\Server__32bit.php:2469
   60.3266   19185680   7. pocketmine\network\RakLibInterface->process() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\network\Network__32bit.php:159
   60.3266   19185712   8. raklib\server\ServerHandler->handlePacket() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\network\RakLibInterface.php:79
   60.3274   19193528   9. pocketmine\network\RakLibInterface->openSession() C:\Users\darre\Downloads\PocketMine-MP\src\raklib\server\ServerHandler__32bit.php:115
   60.3439   19207120  10. pocketmine\Player->__construct() C:\Users\darre\Downloads\PocketMine-MP\src\pocketmine\network\RakLibInterface.php:126

[16:36:50] [EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:36:51] [EMERGENCY]: Please upload the "C:\Users\darre\Downloads\PocketMine-MP\CrashDump_Sun_Nov_22-16.36.50-ALMT_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
 another error

**Comment by keithkfng** [comment]
That might be the quickest fix I've ever seen! Maybe it would work, I've still got a copy of them anyway. Yes, just delete them, that might solve the problem quicker.

**Comment by keithkfng** [comment]
@da123rrell once @mwvent has removed the files, try recompiling and running it again. Might work, most likely

**Comment by da123rrell** [comment]
ok

**Comment by keithkfng** [comment]
Actually did it myself, sorry for the confusion. @da123rrell try recompiling again and run it.

**Comment by da123rrell** [comment]
ok... again

**Comment by keithkfng** [comment]
You may also want to check if the skin, inventory and chest bugs have been fixed or not. If they have, can you please send a link to the phar? Thanks!

**Comment by da123rrell** [comment]
another error

**Comment by da123rrell** [comment]
[16:43:46] [INFO]: da123rrell[/192.168.0.10:19132] logged out due to client disconnect
[16:44:01] [INFO]: da123rrell[/192.168.0.10:19132] logged out due to Login timeout
[16:44:18] [INFO]: da123rrell[/192.168.0.10:19132] logged out due to Login timeout

**Comment by keithkfng** [comment]
What error?

**Comment by kam187** [comment]
No error, it just fails to login, and times out.

**Comment by keithkfng** [comment]
Login packet issue...

**Comment by da123rrell** [comment]
yea and it failed 3 times in a row

**Comment by keithkfng** [comment]
@kam187 go here https://github.com/ImagicalCorp to accept invitation!

**Comment by da123rrell** [comment]
its not even loading

**Comment by keithkfng** [comment]
@da123rrell Hm... Try restarting your server

**Comment by da123rrell** [comment]
ok

**Comment by kam187** [comment]
Hmm it's a code issue for sure.  Is it working for you?

**Comment by da123rrell** [comment]
still broken

**Comment by keithkfng** [comment]
Show me a screenshot of your console.

**Comment by kam187** [comment]
Hmm i'm a bit confused.  There seem to be some changes in the main files but the __64 and __32 are not changed in some cases.  What exactly are the __32 and __64 files?

**Comment by da123rrell** [comment]
![image](https://cloud.githubusercontent.com/assets/11820821/11323366/4924ee2e-9143-11e5-9215-6f7f089b90e0.png)

**Comment by keithkfng** [comment]
I don’t think you actually need them, even @mwvent said they weren’t in the main repo. Obviously, they’re not needed.

**Comment by keithkfng** [comment]
@da123rrell with you logging in, not just the start log

**Comment by da123rrell** [comment]
ooh ok
![image](https://cloud.githubusercontent.com/assets/11820821/11323375/8f0e9a02-9143-11e5-98af-bf7a32b7b803.png)

**Comment by da123rrell** [comment]
there you go

**Comment by kam187** [comment]
$ rm src/pocketmine/network/protocol/LoginPacket__32bit.php 
$ rm src/pocketmine/network/protocol/LoginPacket__64bit.php 

$ rm src/pocketmine/Server__32bit.php 
$ rm src/pocketmine/Server__64bit.php 

and it's ok

**Comment by da123rrell** [comment]
ooh and the skin patch branch doesn't have that problem

**Comment by da123rrell** [comment]
it just has this problem 
![image](https://cloud.githubusercontent.com/assets/11820821/11323407/5fca9a74-9144-11e5-8195-0238fc3fe600.png)

**Comment by kam187** [comment]
At a guess i suppose you have a script somewhere which generates 32 bit and 64 bit versions of some code.  Looking at the LoginPacket code alone it looks like it just strips the top 32 bits in 64 bit systems.  Maybe it's for some optimised version of PHP or something.

Anyway yeah it looks like all the issues are because your master has left over __32 and __64 bit files.  Everyone is committing the main files but the 32/64 bit versions (old random code) is being run as well.

If you have a 32 bit system it may work or vice versa, which is why some people see it working and others don't.

If that's the case you should remove __32 and __64 bit versions from the master repo.

**Comment by da123rrell** [comment]
an don the skin patch you can open chest and the skin IS fixed but you cant put blocks on c mode and logs change to chest when putten on survival

**Comment by keithkfng** [comment]
Okay

**Comment by kam187** [comment]
cd src
find ./ -name "*__??bit.php" -exec rm -rf {} \;

Working fine.  What's with the verbose logging tho:

DataPacket: 0xa7
SendSlot: 9
SelectedSlot: 0
RealBlockSlot: 0
Index:-1
MobEquipmentPacket: Air

**Comment by keithkfng** [comment]
Try the skin-patch branch seems to be working better than master

**Comment by kam187** [comment]
Hmm you can't select blocks in creative with the skin branch.

**Comment by keithkfng** [comment]
Merged pull request with master. I remember commits in master fixed the glitch. Did you recompile and start it again?

**Comment by DRedDogPE** [comment]
I cant be on much today (if at all) so sorry if i cant be of help

**Comment by kam187** [comment]
I'm using the raw code, i don't bother compiling to .phar for quick tests.  Anyway it's the best way to know only the source i have is running and not a stale phar build :)

**Comment by keithkfng** [comment]
@ZombiePower could fix this, I'm n

**Comment by keithkfng** [comment]
@ZombiePower could fix this, I'm not sure how to fix it myself

**Comment by kam187** [comment]
Hmm definitely doesn't work.  It looks like the skin brach was behind and has overwritten the fix.

**Comment by keithkfng** [comment]
We can revert some changes, but I think lets just wait for a fix.

**Comment by kam187** [comment]
Hmm it's a fairly significant problem i think.  What was wrong with the version we had before the merge?

I.e. what's the benefits of the skin branch vs the previous one?

**Comment by keithkfng** [comment]
Skin branch fixes skins and chests fully

**Comment by LouisBHirst** [comment]
keith thanks for inviting me - are you on kik or skype?  I'd like to quickly hash a few things out with you

**Comment by keithkfng** [comment]
I have twitter but none of the others

**Comment by Driesboy** [comment]
can you invite my

**Comment by kam187** [comment]
Hmm i think you should revert the skin merge and let whoever made it merge in the relevant parts properly.  I'm looking through the code and it's clobbered a bunch of other fixes.

**Comment by keithkfng** [comment]
Revert. Then what?

**Comment by LouisBHirst** [comment]
kam - can you give an example?  I diffed master & skin-fix and the only change is for chests

**Comment by kam187** [comment]
Hmm actually you're right, i was looking at the wrong directory!

**Comment by LouisBHirst** [comment]
I tried this phar.  There's a lot of things wrong with it, at least for my testing.  Blocks could be placed but they were the wrong ones.  Also I think rcon calls were killing the server.

**Comment by LouisBHirst** [comment]
Actually Kam i'm going to go back and agree with you.  I think there may have been an issue with the commits.  For example take a look at ContainerSetSlotPacket.php.  There was perhaps a fix in that for master that isn't present in skin-fix.

**Comment by keithkfng** [comment]
It was merged, so I'd imagine it would be fixed. I'm not sure though, I haven't tested it myself.
