### ISSUE TITLE
Fork the official repo?

### ISSUE THREAD

**Issue by legoboy0215** [ImagicalCorp/PocketMine-0.13.0#74]
Just a question: Can someone good with git do this? Or...

**Comment by TahaTheHacker** [comment]
just create an empty repo without README.md and click that thing that means "Copy another code" and follow steps.
```without git```

**Comment by legoboy0215** [comment]
Then why isn't anyone using it?

**Comment by thebigsmileXD** [comment]
I directly sync the folder to eclipse, edit, push via github desktop and then check travis. So i don't need to fork
