### ISSUE TITLE
C-Mode

### ISSUE THREAD

**Issue by SirGamer** [ImagicalCorp/PocketMine-0.13.0#75]
I just compiled the current src folder, there is 1 bugg.

Users cannot build in c-mode.

Thanks for taking your time to read this.

 :)

**Comment by deotern** [comment]
Please don't use latest source code, as it doesn't release yet, it may be 100% bugged.. :(
Please choose release versions at:
pocketmine.minedox.com

**Comment by SirGamer** [comment]
Ok.

**Comment by SirGamer** [comment]
Did you create that with WP? Because you created minedox.com with WordPress..

**Comment by EnderKenji** [comment]
Deot, the latest release can let player get in the server, keep disconnect. 

I think this problem is related to SimpleAuth. Checked it thru console

**Comment by deotern** [comment]
@SirGamer Nope, its with single file :) I created Minedox Website with WP is because theres many pages, but since pocketmine.minedox.com has only one page, its easier to create with default.html :)

**Comment by deotern** [comment]
@EnderKenji zombie_power has been assigned on this, we will try to fix it ASAP ;)
