### ISSUE TITLE
A bugg, when I clicked an enchanting table in the c-mode inventory

### ISSUE THREAD

**Issue by ghost** [ImagicalCorp/PocketMine-0.13.0#78]
PocketMine-MP Crash Dump Sun Nov 22 05:16:22 AKST 2015

Error: Call to undefined method pocketmine\tile\Chest::getTile()
File: /src/pocketmine/tile/Chest
Line: 65
Type: E_ERROR

Code:
[56] 		}
[57] 	}
[58] 
[59] 	public function close(){
[60] 		if($this->closed === false){
[61] 			foreach($this->getInventory()->getViewers() as $player){
[62] 				$player->removeWindow($this->getInventory()); 
[63] 			}
[64] 
[65] 			foreach($this->getTile()->getInventory() as $chest){
[66] 				$chest->removeWindow($this->getRealInventory()); 
[67] 			}
[68] 			parent::close();
[69] 		}
[70] 	}
[71] 
[72] 	public function saveNBT(){
[73] 		$this->namedtag->Items = new Enum("Items", []);
[74] 		$this->namedtag->Items->setTagType(NBT::TAG_Compound);
[75] 		for($index = 0; $index < $this->getSize(); ++$index){

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/level/format/generic/BaseFullChunk(402): pocketmine\tile\Chest->close(boolean)
#2 /src/pocketmine/level/format/mcregion/McRegion__32bit(225): pocketmine\level\format\generic\BaseFullChunk->unload(boolean)
#3 /src/pocketmine/level/Level__32bit(2612): pocketmine\level\format\mcregion\McRegion->unloadChunk(boolean)
#4 /src/pocketmine/level/Level__32bit(2894): pocketmine\level\Level->unloadChunk(boolean)
#5 /src/pocketmine/level/Level__32bit(686): pocketmine\level\Level->unloadChunks(boolean)
#6 /src/pocketmine/Server(2328): pocketmine\level\Level->doTick(boolean)
#7 /src/pocketmine/Server(2486): pocketmine\Server->checkTickUpdates(boolean)
#8 /src/pocketmine/Server(2226): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(2104): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(1705): pocketmine\Server->start(boolean)
#11 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(boolean)
#12 /src/pocketmine/PocketMine(0): {main}(boolean)

PocketMine-MP version: 1.7dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT SirGamer 6.1 (Windows 10) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Please fix this ASAP.

- Best Regards,

SirGamer

**Comment by TahaTheHacker** [comment]
Blame @ZombiePower the  bugger

**Comment by SirGamer** [comment]
Lol.

**Comment by matcracker** [comment]
Use the dev 39 not dev 0

**Comment by thebigsmileXD** [comment]
The enchantingtable inventory doesn't even exist yet.. No idea if i could do it.

**Comment by legoboy0215** [comment]
lol $chest is already a tile. Why getTile()???

**Comment by ZombiePower** [comment]
@TahaTheHacker if you get do jack shit, get the fuck out of here

**Comment by ZombiePower** [comment]
I may need some help on this @legoboy0215 ?

**Comment by thebigsmileXD** [comment]
@ZombiePower Write such comment again and you can leave the repo forever
Taha wasn't even in the conversation, so i am sure you mean me. Calm your tongue!

**Comment by ZombiePower** [comment]
no... I deleted his comment.

**Comment by ZombiePower** [comment]
he has been pissing off lately. @thebigsmileXD sorry if you think, the message was for you

**Comment by legoboy0215** [comment]
Please don't fight. Be nice :P

**Comment by robske110** [comment]
How about just removing the enchantment Table?
(OnBlockPlace,ifBlockID,Remove)
Don't know the exact syntnax, but this should prevent it from crashing!
&I can only program some plugins&

**Comment by keithkfng** [comment]
It's been fixed by @ZombiePower already.

**Comment by ZombiePower** [comment]
Enchanting tables aren't crashing xD
