### ISSUE TITLE
Furnace MCPE Crash

### ISSUE THREAD

**Issue by TahaTheHacker** [ImagicalCorp/PocketMine-0.13.0#79]
Hello,

i've found a  bug, when you open a furnace MCPE Crashes,
i actually don't know what's cuasing it.

thanks

**Comment by iTzAnTiFTW** [comment]
Hello, This issue also has some problems when smelting.

**Comment by matcracker** [comment]
For fix it, we must update the NBT tags on php7

**Comment by ZombiePower** [comment]
so, when you add stuff to a furnace.. it crashed your server? or is it when you start smelting?

**Comment by matcracker** [comment]
This issue happend when you place the furnace and left the server. When you rejoin, the client crash but if you place a new furnace you can open it without crash.

**Comment by ZombiePower** [comment]
I am a little confused. So, you placed the furnace, left the server and crashed?

**Comment by matcracker** [comment]
With build 39

**Comment by ZombiePower** [comment]
Let him fix it... he thinks he is better than everyone

**Comment by matcracker** [comment]
Follow this steps:
1- Place a furnace (It works if you open it)
2- Left the server.
3- Rejoin ther server and if you try to open the furnace the client crash

**Comment by keithkfng** [comment]
You should be able to go into the furnace now, but no smelting. Mentioned the issue in another one. Doesn't crash anymore.

**Comment by MasterWolf** [comment]
in build #144 its crashing again

**Comment by PocketKiller** [comment]
@ZombiePower i didn't say i am better than everyone.
@MasterWolf try another build.. is it crashing for you?

**Comment by thebigsmileXD** [comment]
New release.. try there
