### ISSUE TITLE
setTime() broken

### ISSUE THREAD

**Issue by deotern** [ImagicalCorp/PocketMine-0.13.0#90]
I test to use setTime(5000) with API and command, both are not working... 5000 should be in morning... but it gives me night... Maybe theres something wrong with setTime API or Time Cycle Value thingy
![screenshot_2015-11-23-11-38-58](https://cloud.githubusercontent.com/assets/14260477/11329450/479a4358-91d7-11e5-9752-43025073a2b1.png)

**Comment by matcracker** [comment]
If you use normal command, do it works?

**Comment by deotern** [comment]
Nope, command don't work either... tried...
I tested, it's not Time Cycle Bug
Bug is at the API setTime()

**Comment by TahaTheHacker** [comment]
5000 is nearly night...
0 is day.

**Comment by Rodrigo294X** [comment]
I noticed something about this command that can is related to this bug . When I type the command 
"/time set night" is not night , it goes to the time 0 .

**Comment by matcracker** [comment]
Can be a new protocol update?

**Comment by matcracker** [comment]
A temporary fix it's to change the time values, so the time change correctly but with ticks wrong

**Comment by keithkfng** [comment]
Lel

**Comment by NML32** [comment]
Usage: /time <set|add> <value> OR /time <start|stop|query>
worked for me with the latest build. Or are we talking about a different command.

**Comment by keithkfng** [comment]
Okay...

**Comment by deotern** [comment]
Well, is it fixed yet? Someone pls reference a PR/commit for this issue if its fixed...
And, @TahaTheHacker I used 5000 from very old times till now, its nearly noon! not night... >< Pls check it yourself http://minecraft.gamepedia.com/Day-night_cycle

**Comment by keithkfng** [comment]
@matcracket fixed or what?

**Comment by deotern** [comment]
Well, idk... Thats why i asking someone to reference this issue to a commit/PR id its fixed...

**Comment by Rodrigo294X** [comment]
but "/time set night" not is set to night. It set to 14000(still is day) . I suggest you put to 17000 (when it's night)

**Comment by matcracker** [comment]
No, it isn't fixed yet! I don't know if it's a bug releated client or a new tick update. After I made a PR for a temporary fix.

**Comment by keithkfng** [comment]
Pull request? I don't see any...

**Comment by matcracker** [comment]
I wrote "after" xD

**Comment by keithkfng** [comment]
Well, have you found a temporary fix or not? It sounds confusing to me, maybe because I need to learn more english(jk)

**Comment by matcracker** [comment]
Yes, I found temporary fix.

**Comment by keithkfng** [comment]
Can you submit a PR?

**Comment by matcracker** [comment]
OMG, I try to change ticks for each cycle and when you close the server it changes all D:

**Comment by keithkfng** [comment]
Ok... Lol

**Comment by ZombiePower** [comment]
I think it works now
