### ISSUE TITLE
Server not connecting in #143

### ISSUE THREAD

**Issue by MCDad** [ImagicalCorp/PocketMine-0.13.0#92]
I'm using #143 running on a Raspberry Pi2 connecting from an iPad running 0.13.0.

Server is located.  When I attempt to connect I says "Generating world  Building Terrain" then "Server Time Out"  after about 3 seconds (if I remember correctly).  Exactly the same set up, but using build 72 and there's no issues connecting.

**Comment by keithkfng** [comment]
Console please...

**Comment by ZombiePower** [comment]
there is no issue in build 72? or there is?

**Comment by MCDad** [comment]
No issue in 72. I can connect and enter worlds no problem. On way to work
now. Will post console when I get home tonight or early tomorrow. Sorry

**Comment by da123rrell** [comment]
Isnt this fixed on #144

**Comment by matcracker** [comment]
Use the dev 144 or up, it's fixed.

**Comment by MCDad** [comment]
Yes.  Fixed in 144.  Keith you get up earlier than me.  Thanks guys.

**Comment by keithkfng** [comment]
Hahaha I beat you
