### ISSUE TITLE
Crafting & furnace issues

### ISSUE THREAD

**Issue by da123rrell** [ImagicalCorp/PocketMine-0.13.0#97]
title says everything. from the latest one

**Comment by keithkfng** [comment]
Crafting is a glitch. Will fix soon.

**Comment by da123rrell** [comment]
ok

**Comment by da123rrell** [comment]
oh and ow I can open furnance but cant smelt

**Comment by keithkfng** [comment]
Okay... Furnace as well.

**Comment by ZombiePower** [comment]
Will work on this issue tomorrow

**Comment by keithkfng** [comment]
Thanks!

**Comment by MasterWolf** [comment]
Plz help. How can i download your commite as .phar file? Im new in github :)

**Comment by keithkfng** [comment]
Seriously... READ THE README FILE!

**Comment by MasterWolf** [comment]
Ok. Wait.

**Comment by MasterWolf** [comment]
I know how to download release and build. But i dont know how to download commit. :(. How to download commit?

**Comment by keithkfng** [comment]
Download commit? What commit?

**Comment by MasterWolf** [comment]
Any commit

**Comment by MasterWolf** [comment]
Here is lot of commits

**Comment by keithkfng** [comment]
You can't download commits...

**Comment by MasterWolf** [comment]
:(. But thanks for information!

**Comment by keithkfng** [comment]
You can fork the repo(which means create a copy of this repo to your account) though

**Comment by da123rrell** [comment]
just download this
https://github.com/ImagicalCorp/PocketMine-0.13.0/archive/master.zip

**Comment by thebigsmileXD** [comment]
We'll have to add shaped recipies. For everything

**Comment by keithkfng** [comment]
Yep...

**Comment by thebigsmileXD** [comment]
About crafting. Would like to know what blocks/items are exactly bugged. I know how to fix now

**Comment by da123rrell** [comment]
door

**Comment by ZombiePower** [comment]
Yes, before I want to fix it, before I actually leave : )

**Comment by ZombiePower** [comment]
I was having a look at crafting manager (just had a peek). If you can tell me the location, I will fix it, from there on :)

**Comment by keithkfng** [comment]
Can you also fix the furnace bug before you leave?

**Comment by thebigsmileXD** [comment]
Jup. Its crafting manager. Door: confirmed. Ao boats also. You know you can craft chained armor with fire blocks??

**Comment by keithkfng** [comment]
Lel

**Comment by ZombiePower** [comment]
Yes :)

**Comment by da123rrell** [comment]
And you also cant craft diamond pickaxe (i think)

**Comment by ZombiePower** [comment]
Crafting fixed (not confirmed) and working on furnaces, is anyone going to add Anvil in tile? XD
